---
title: "Digital History in Finland, 1488-1828"
author: "Leo Lahti"
date: "March 3, 2016"
output: markdown_document
---

```{r 20160303-init, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)
library(bibliographica)
library(fennica)
library(sorvi)

# Nice theme
theme_set(theme_bw(26))

# Read data
dfo <- readRDS("df.Rds")

# Add publication decade
# TODO add already in the original preprocessed data matrix
dfo$publication_decade <- 10*floor(dfo$publication_year/10)

# Remove very early and late years
dfo <- dfo %>% filter(publication_year > 1400 & publication_year < 1911)
```


```{r 20160303-turkuvsother, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
# Let us focus on years 1400-1828
df <- dfo %>% filter(publication_year > 1400 & publication_year < 1829) %>%
      filter(!is.na(country)) %>%
      filter(!is.na(publication_place) & !is.na(paper) & paper > -0.01)

# Add indicator field: Turku or Not Turku
myplace <- "Turku"

df$myplace <- rep(NA, nrow(df))
df$myplace[df$publication_place == myplace] <- myplace
df$myplace[!df$publication_place == myplace & df$country == "Finland"] <- "Finland"
df$myplace[!df$country == "Finland" & !df$publication_place == myplace] <- "Foreign"
df$myplace <- factor(df$myplace, levels = rev(c("Foreign", "Finland", "Turku")))


# Keep entries with known publication place and paper consumption
# Group by year/decade and Turku/Other
dfs <- df %>% group_by(publication_decade, myplace) %>%
  summarise(titles = n(), paper = sum(paper, na.rm = TRUE))

p <- ggplot(dfs, aes(x = publication_decade, y = paper, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Paper consumption") +
     #scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE, title = "")) + 
     xlab("Publication decade") + ylab("Paper")
print(p)

pdf("20160303-paper.pdf", width = 12, height = 9)
print(p)
dev.off()

jpeg("20160303-paper.jpg", quality = 100, height = 480, width = 600)
print(p)
dev.off()


p <- ggplot(dfs, aes(x = publication_decade, y = titles, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Title count") +
     # scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE, title = "")) +      
     xlab("Publication decade") + ylab("Title count (n)")
print(p)

pdf("20160303-titles.pdf", width = 12, height = 9)
print(p)
dev.off()

jpeg("20160303-titles.jpg", quality = 100, height = 480, width = 600)
print(p)
dev.off()
```
