---
title: "Digital History in Finland, 1488-1828"
author: "Leo Lahti"
date: "December 9, 2015"
output: markdown_document
---

This markdown document contains presentation material for [Digital History in Finland seminar (University of Helsinki, Dec 9, 2015)](http://blogs.helsinki.fi/mstolone/2015/09/21/call-for-papers-digital-history-in-finland-wednesday-9-12-2015/). The source code to reproduce the figures is in the [Rmarkdown document](https://github.com/COMHIS/fennica/blob/master/inst/examples/20151209-HelsinkiDH.Rmd).


```{r 20151209-HDH-init, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)

library(fennica)
library(sorvi)

# Nice theme
theme_set(theme_bw(20))

# Read data
dfo <- readRDS("df.Rds")

# Add publication decade
# TODO add already in the original preprocessed data matrix
dfo$publication_decade <- 10*floor(dfo$publication_year/10)

# Remove very early and late years
dfo <- dfo %>% filter(publication_year > 1400 & publication_year < 1911)
```


```{r 20151209-HDH-TurkuVSOthers, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
# Let us focus on years 1400-1828
df <- dfo %>% filter(publication_year > 1400 & publication_year < 1829) %>%
      filter(!is.na(country)) %>%
      filter(!is.na(publication_place) & !is.na(paper) & paper > -0.01)

# Add indicator field: Turku or Not Turku
myplace <- "Turku"

df$myplace <- rep(NA, nrow(df))
df$myplace[df$publication_place == myplace] <- myplace
df$myplace[!df$publication_place == myplace & df$country == "Finland"] <- "Finland"
df$myplace[!df$country == "Finland" & !df$publication_place == myplace] <- "Foreign"
df$myplace <- factor(df$myplace, levels = rev(c("Foreign", "Finland", "Turku")))


# Keep entries with known publication place and paper consumption
# Group by year/decade and Turku/Other
dfs <- df %>% group_by(publication_decade, myplace) %>%
  summarise(titles = n(), paper = sum(paper, na.rm = TRUE))

p <- ggplot(dfs, aes(x = publication_decade, y = paper, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Paper consumption") +
     #scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE)) + 
     xlab("Publication decade") + ylab("Paper")
print(p)

p <- ggplot(dfs, aes(x = publication_decade, y = titles, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Title count") +
     # scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE)) +      
     xlab("Publication decade") + ylab("Title count (n)")
print(p)
```



```{r 20151209-HDH-Author, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=6}
p1 <- top_plot(dfo, "author", 10) + ggtitle(paste("Top authors (", min(na.omit(dfo$publication_year)), "-", max(na.omit(dfo$publication_year)), ")", sep = "")) + ylab("Title count (n)")
print(p1)

p2 <- top_plot(df, "author", 10) + ggtitle(paste("Top authors (", min(na.omit(df$publication_year)), "-", max(na.omit(df$publication_year)), ")", sep = "")) + ylab("Title count (n)")
print(p2)
```


```{r 20151209-HDH-topauthor, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
# Top author
topa <- names(rev(sort(table(dfo$author))))[1:2]

dfs <- dfo %>% filter(author %in% topa) %>% group_by(author, publication_decade) %>% summarize(paper = sum(paper, na.rm = T), titles = n())

p1 <- p2 <- ggplot(dfs, aes(x = publication_decade, y = titles, color = author)) + geom_point() + geom_line(size = 2) + scale_color_manual(values = c("blue", "red")) + ggtitle("Title count") + xlab("Publication decade") + ylab("Title count (n)")
print(p1)

p2 <- ggplot(dfs, aes(x = publication_decade, y = paper, color = author)) + geom_point() + geom_line(size = 2) + scale_color_manual(values = c("blue", "red")) + ggtitle("Paper consumption") + xlab("Publication decade") + ylab("Paper")
print(p2)
```

```{r 20151209-HDH-topplace, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=6}
p1 <- top_plot(dfo, "publication_place", 10) + ylab("Title count (n)") + ggtitle(paste("Top publication places (", min(na.omit(dfo$publication_year)), "-", max(na.omit(dfo$publication_year)), ")", sep = ""))
print(p1)

p2 <- top_plot(df, "publication_place", 10) + ylab("Title count (n)") + ggtitle(paste("Top publication places (", min(na.omit(df$publication_year)), "-", max(na.omit(df$publication_year)), ")", sep = ""))
print(p2)
```

```{r 20151209-HDH-toptopic, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=6}
p1 <- top_plot(dfo, "topic", 10) + ylab("Title count (n)") + ggtitle(paste("Top themes (", min(na.omit(dfo$publication_year)), "-", max(na.omit(dfo$publication_year)), ")", sep = ""))
print(p1)

p2 <- top_plot(df, "topic", 10) + ylab("Title count (n)") + ggtitle(paste("Top themes (", min(na.omit(df$publication_year)), "-", max(na.omit(df$publication_year)), ")", sep = ""))
print(p2)
```

```{r 20151209-HDH-topg, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=5, fig.width=9}
topg <- setdiff(names(rev(sort(table(dfo$gatherings))))[1:6], "NA")
dfs <- dfo %>%
    filter(gatherings %in% topg & publication_year > 1650) %>%
    group_by(publication_decade, gatherings) %>% tally()
dfs$gatherings <- order_gatherings(dfs$gatherings)    
p <- ggplot(dfs, aes(x = publication_decade, y = n, color = gatherings)) + geom_point(size = 3) + geom_smooth(fill = "lightgray", size = 2, alpha = 0.2) + ggtitle("Top gatherings timeline") + ylim(c(0, max(dfs$n))) + xlab("Publication decade") + ylab("Title count (n)")
print(p)
```