source("R/placenames.R", encoding="UTF-8")

df$publication_place <- preprocess_placenames(df$publication_place)

unique_cities <- unique(df$publication_place)

# -------------------------------------------------------------------------------------------------------------------------------------------------------------

unique_cities <- collect_misspellings("almena",c("Almena","Almena WI","Almena Wis","Almena Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("altdorf",c("Altdorf"),unique_cities)
unique_cities <- collect_misspellings("ashtabula",c("Ashtabula","Ashtabula OH","Ashtabula Ohio"),unique_cities)
unique_cities <- collect_misspellings("astoria",c("Astoria","Astoria OR","Astoria Ore","Astoria Oregon"),unique_cities)
unique_cities <- collect_misspellings("berliini",c("Berliini","Berlin"),unique_cities)
unique_cities <- collect_misspellings("boston",c("Boston","Boston MA","Boston Mass","Boston Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("bridgeport",c("Bridgeport","Bridgeport CT","Bridgeport Conn","Bridgeport Connecticut"),unique_cities)
unique_cities <- collect_misspellings("bronx",c("Bronx","Bronx NY","Bronx New York"),unique_cities)
unique_cities <- collect_misspellings("brooklyn",c("Brooklyn","Brooklyn NY","Brooklyn New York"),unique_cities)
unique_cities <- collect_misspellings("calumet",c("Calumet","Calumet MI","Calumet Mich","Calumet Michigan"),unique_cities)
unique_cities <- collect_misspellings("chicago",c("Chicago","Chicago IL","Chicago Ill","Chicago Illinois"),unique_cities)
unique_cities <- collect_misspellings("chisholm",c("Chisholm","Chisholm MN","Chisholm Minn","Chisholm Minnesota"),unique_cities)
unique_cities <- collect_misspellings("cincinnati",c("Cincinnati","Cincinnati OH","Cincinnati Ohio"),unique_cities)
unique_cities <- collect_misspellings("cleveland",c("Cleveland","Cleveland OH","Cleveland Ohio"),unique_cities)
unique_cities <- collect_misspellings("duluth",c("Duluth","Duluth MN","Duluth Minn","Duluth Minnesota"),unique_cities)
unique_cities <- collect_misspellings("espoo",c("Espoo","Esbo"),unique_cities)
unique_cities <- collect_misspellings("fitchburg",c("Fitchburg","Fitchburg MA","Fitchburg Mass","Fitchburg Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("giessen",c("Giessen","Giessae","Giessae Cattorum"),unique_cities)
unique_cities <- collect_misspellings("goteborg",c("Göteborg","Gothenburg"),unique_cities)
unique_cities <- collect_misspellings("gottingen",c("Göttingen","Goettingae"),unique_cities)
unique_cities <- collect_misspellings("greifswald",c("Greifswald","Gryphiswaldae"),unique_cities)
unique_cities <- collect_misspellings("haaparanta",c("Haaparanta","Haparanda"),unique_cities)
unique_cities <- collect_misspellings("hamina",c("Hamina","Haminassa","Fredrikshamn"),unique_cities)
unique_cities <- collect_misspellings("hampuri",c("Hampuri","Hamburg"),unique_cities)
unique_cities <- collect_misspellings("hancock",c("Hancock","Hancock MI","Hancock Mich", "Hancock Michigan"),unique_cities)
unique_cities <- collect_misspellings("hanko",c("Hanko","Hangö"),unique_cities)
unique_cities <- collect_misspellings("helsinki",c("Helsinki","Helsingissä","Helsingfors"),unique_cities)
unique_cities <- collect_misspellings("hameenlinna",c("Hämeenlinna","Hämeenlinnassa","Tavastehus"),unique_cities)
unique_cities <- collect_misspellings("ironwood",c("Ironwood","Ironwood MI","Ironwood Mich","Ironwood Michigan"),unique_cities)
unique_cities <- collect_misspellings("ishpeming",c("Ishpeming","Ishpeming MI","Ishpeming Mich","Ishpeming Michigan"),unique_cities)
unique_cities <- collect_misspellings("jena",c("Jena"),unique_cities)
unique_cities <- collect_misspellings("jyvaskyla",c("Jyväskylä","Jyväskylässä"),unique_cities)
unique_cities <- collect_misspellings("kaleva",c("Kaleva","Kaleva MI","Kaleva Mich","Kaleva Michigan"),unique_cities)
unique_cities <- collect_misspellings("kaliningrad",c("Kaliningrad","Königsberg","Regiomonti Borussorum"),unique_cities)
unique_cities <- collect_misspellings("karjaa",c("Karjaa","Karis"),unique_cities)
unique_cities <- collect_misspellings("kaskinen",c("Kaskinen","Kaskö"),unique_cities)
unique_cities <- collect_misspellings("kiel",c("Kiel","Kiliae"),unique_cities)
unique_cities <- collect_misspellings("kokkola",c("Kokkola","Gamlakarleby"),unique_cities)
unique_cities <- collect_misspellings("kotka",c("Kotka","Kotkassa"),unique_cities)
unique_cities <- collect_misspellings("kouvola",c("Kouvola"),unique_cities)
unique_cities <- collect_misspellings("kristiinankaupunki",c("Kristiinankaupunki","Kristinestad"),unique_cities)
unique_cities <- collect_misspellings("kruunupyy",c("Kruunupyy","Kronoby"),unique_cities)
unique_cities <- collect_misspellings("kuopio",c("Kuopio","Kuopiossa"),unique_cities)
unique_cities <- collect_misspellings("koln",c("Köln","Cologne"),unique_cities)
unique_cities <- collect_misspellings("koopenhamina",c("Kööpenhamina","Köbenhavn","Copenhagen"),unique_cities)
unique_cities <- collect_misspellings("lappeenranta",c("Lappeenranta","Lappeenrannassa","Willmanstrand"),unique_cities)
unique_cities <- collect_misspellings("lahti",c("Lahti"),unique_cities)
unique_cities <- collect_misspellings("leiden",c("Leiden","Lugduni Batauorum","Lvgdvni Batavorvm"),unique_cities)
unique_cities <- collect_misspellings("linkoping",c("Linköping"),unique_cities)
unique_cities <- collect_misspellings("lontoo",c("Lontoo","London","Londres"),unique_cities)
unique_cities <- collect_misspellings("loviisa",c("Loviisa"),unique_cities)
unique_cities <- collect_misspellings("lund",c("Lund","Lundae","Londini Gothorum","Londini Scanorum"),unique_cities)
unique_cities <- collect_misspellings("lyypekki",c("Lyypekki","Lübeck"),unique_cities)
unique_cities <- collect_misspellings("maarianhamina",c("Maarianhamina","Mariehamn"),unique_cities)
unique_cities <- collect_misspellings("magdeburg",c("Magdeburg","Magdaeburgi"),unique_cities)
unique_cities <- collect_misspellings("marburg",c("Marburg","Marpurgi Cattorum","Marpvrgi Cattorvm"),unique_cities)
unique_cities <- collect_misspellings("mikkeli",c("Mikkeli","Mikkelissä","St Mikkeli","St Michel"),unique_cities)
unique_cities <- collect_misspellings("milwaukee",c("Milwaukee","Milwaukee WI","Milwaukee Wis","Milwaukee Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("minneapolis",c("Minneapolis","Minneapolis MN","Minneapolis Minn","Minneapolis Minneasota"),unique_cities)
unique_cities <- collect_misspellings("moskova",c("Moskova","Moskau"),unique_cities)
unique_cities <- collect_misspellings("nanaimo",c("Nanaimo","Nanaimo BC"),unique_cities)
unique_cities <- collect_misspellings("narva",c("Narva"),unique_cities)
unique_cities <- collect_misspellings("newyork",c("New York","New York NY","New York New York"),unique_cities)
unique_cities <- collect_misspellings("newyorkmills",c("New York Mills","New York Mills MN","New York Mills Minn"),unique_cities)
unique_cities <- collect_misspellings("oslo",c("Oslo","Kristiania","Christiania"),unique_cities)
unique_cities <- collect_misspellings("oulu",c("Oulu","Oulussa","Uleåborg"),unique_cities)
unique_cities <- collect_misspellings("pariisi",c("Pariisi","Paris"),unique_cities)
unique_cities <- collect_misspellings("philadelphia",c("Philadelphia","Philadelphia PA","Philadelphia Penn","Philadelphia Pennsylvania"),unique_cities)
unique_cities <- collect_misspellings("pietari",c("Pietari","Pietarissa","St Peterburg","St Petersburg","Petrograd"),unique_cities)
unique_cities <- collect_misspellings("pietarsaari",c("Pietarsaari","Jakobstad"),unique_cities)
unique_cities <- collect_misspellings("pori",c("Pori","Porissa","Björneborg"),unique_cities)
unique_cities <- collect_misspellings("portland",c("Portland","Portland OR","Portland Oregon"),unique_cities)
unique_cities <- collect_misspellings("porvoo",c("Porvoo","Porvoossa","Borgå"),unique_cities)
unique_cities <- collect_misspellings("parnu",c("Pärnu"),unique_cities)
unique_cities <- collect_misspellings("portarthur",c("Port Arthur","Port Arthur ON","Port Arthur Ont","Port Arthur Ontario"),unique_cities)
unique_cities <- collect_misspellings("quincy",c("Quincy","Quincy MA","Quincy Mass","Quincy Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("rauma",c("Rauma","Raumalla"),unique_cities)
unique_cities <- collect_misspellings("riika",c("Riika","Riga"),unique_cities)
unique_cities <- collect_misspellings("rockisland",c("Rock Island","Rock Island IL","Rock Island Ill","Rock Island Illinois"),unique_cities)
unique_cities <- collect_misspellings("rooma",c("Rooma"),unique_cities)
unique_cities <- collect_misspellings("rostock",c("Rostock","Rostochii"),unique_cities)
unique_cities <- collect_misspellings("seattle",c("Seattle","Seattle WA","Seattle Wash","Seattle Washington"),unique_cities)
unique_cities <- collect_misspellings("sipoo",c("Sipoo","Sibbo"),unique_cities)
unique_cities <- collect_misspellings("smithville",c("Smithville","Smithville MN","Smithville Minn","Smithville Minnesota"),unique_cities)
unique_cities <- collect_misspellings("sortavala",c("Sortavala","Sortavalassa"),unique_cities)
unique_cities <- collect_misspellings("strangnas",c("Strängnäs"),unique_cities)
unique_cities <- collect_misspellings("superior",c("Superior","Superior WI","Superior Wis","Superior Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("tallinna",c("Tallinna","Reval"),unique_cities)
unique_cities <- collect_misspellings("tammisaari",c("Tammisaari","Ekenäs"),unique_cities)
unique_cities <- collect_misspellings("tampere",c("Tampere","Tampereella","Tammerfors"),unique_cities)
unique_cities <- collect_misspellings("tartto",c("Tartto","Tartu","Dorpati","Dorpati Livonorum"),unique_cities)
unique_cities <- collect_misspellings("tukholma",c("Tukholma","Tukholmassa","Stockholm"),unique_cities)
unique_cities <- collect_misspellings("turenki",c("Turenki"),unique_cities)
unique_cities <- collect_misspellings("turku",c("Turku","Turussa","Åbo","Aboae","Aboae Finnorum"),unique_cities)
unique_cities <- collect_misspellings("uppsala",c("Uppsala","Uppsalassa"),unique_cities)
unique_cities <- collect_misspellings("uusikaarlepyy",c("Uusikaarlepyy","Nykarleby"),unique_cities)
unique_cities <- collect_misspellings("uusikaupunki",c("Uusikaupunki","Nystad"),unique_cities)
unique_cities <- collect_misspellings("vaasa",c("Vaasa","Vaasassa","Nikolainkaupunki","Nikolainkaupungissa","Nikolaistad"),unique_cities)
unique_cities <- collect_misspellings("viipuri",c("Viipuri","Viipurissa","Viborg"),unique_cities) # huom! Tanskassakin on Viborg
unique_cities <- collect_misspellings("vasteros",c("Västerås","Arosia","Arosiensis","Westrosia"),unique_cities)
unique_cities <- collect_misspellings("wittenberg",c("Wittenberg","Wittenbergae"),unique_cities)
unique_cities <- collect_misspellings("worcester",c("Worcester","Worcester MA","Worcester Mass","Worcester Massachusetts"),unique_cities)

write(unique_cities, file="inst/examples/output.tables/city_others.csv")

# -------------------------------------------------------------------------------------------------------------------------------------------------------------

df$publication_place <- correct_misspellings(df$publication_place,"almena","Almena WI")
df$publication_place <- correct_misspellings(df$publication_place,"altdorf","Altdorf")
df$publication_place <- correct_misspellings(df$publication_place,"ashtabula","Ashtabula OH")
df$publication_place <- correct_misspellings(df$publication_place,"astoria","Astoria OR")
df$publication_place <- correct_misspellings(df$publication_place,"berliini","Berliini")
df$publication_place <- correct_misspellings(df$publication_place,"boston","Boston MA")
df$publication_place <- correct_misspellings(df$publication_place,"bridgeport","Bridgeport CT")
df$publication_place <- correct_misspellings(df$publication_place,"bronx","Bronx NY")
df$publication_place <- correct_misspellings(df$publication_place,"brooklyn","Brooklyn NY")
df$publication_place <- correct_misspellings(df$publication_place,"calumet","Calumet MI")
df$publication_place <- correct_misspellings(df$publication_place,"chicago","Chicago IL")
df$publication_place <- correct_misspellings(df$publication_place,"chisholm","Chisholm MN")
df$publication_place <- correct_misspellings(df$publication_place,"cincinnati","Cincinnati OH")
df$publication_place <- correct_misspellings(df$publication_place,"cleveland","Cleveland OH")
df$publication_place <- correct_misspellings(df$publication_place,"duluth","Duluth MN")
df$publication_place <- correct_misspellings(df$publication_place,"espoo","Espoo")
df$publication_place <- correct_misspellings(df$publication_place,"fitchburg","Fitchburg MA")
df$publication_place <- correct_misspellings(df$publication_place,"giessen","Giessen")
df$publication_place <- correct_misspellings(df$publication_place,"goteborg","Göteborg")
df$publication_place <- correct_misspellings(df$publication_place,"gottingen","Göttingen")
df$publication_place <- correct_misspellings(df$publication_place,"greifswald","Greifswald")
df$publication_place <- correct_misspellings(df$publication_place,"haaparanta","Haaparanta")
df$publication_place <- correct_misspellings(df$publication_place,"hamina","Hamina")
df$publication_place <- correct_misspellings(df$publication_place,"hampuri","Hampuri")
df$publication_place <- correct_misspellings(df$publication_place,"hancock","Hancock MI")
df$publication_place <- correct_misspellings(df$publication_place,"hanko","Hanko")
df$publication_place <- correct_misspellings(df$publication_place,"helsinki","Helsinki")
df$publication_place <- correct_misspellings(df$publication_place,"hameenlinna","Hämeenlinna")
df$publication_place <- correct_misspellings(df$publication_place,"ironwood","Ironwood MI")
df$publication_place <- correct_misspellings(df$publication_place,"ishpeming","Ishpeming MI")
df$publication_place <- correct_misspellings(df$publication_place,"jena","Jena")
df$publication_place <- correct_misspellings(df$publication_place,"jyvaskyla","Jyväskylä")
df$publication_place <- correct_misspellings(df$publication_place,"kaleva","Kaleva MI")
df$publication_place <- correct_misspellings(df$publication_place,"kaliningrad","Kaliningrad")
df$publication_place <- correct_misspellings(df$publication_place,"karjaa","Karjaa")
df$publication_place <- correct_misspellings(df$publication_place,"kaskinen","Kaskinen")
df$publication_place <- correct_misspellings(df$publication_place,"kiel","Kiel")
df$publication_place <- correct_misspellings(df$publication_place,"kokkola","Kokkola")
df$publication_place <- correct_misspellings(df$publication_place,"kotka","Kotka")
df$publication_place <- correct_misspellings(df$publication_place,"kouvola","Kouvola")
df$publication_place <- correct_misspellings(df$publication_place,"kristiinankaupunki","Kristiinankaupunki")
df$publication_place <- correct_misspellings(df$publication_place,"kruunupyy","Kruunupyy")
df$publication_place <- correct_misspellings(df$publication_place,"kuopio","Kuopio")
df$publication_place <- correct_misspellings(df$publication_place,"koln","Köln")
df$publication_place <- correct_misspellings(df$publication_place,"koopenhamina","Kööpenhamina")
df$publication_place <- correct_misspellings(df$publication_place,"lahti","Lahti")
df$publication_place <- correct_misspellings(df$publication_place,"lappeenranta","Lappeenranta")
df$publication_place <- correct_misspellings(df$publication_place,"leiden","Leiden")
df$publication_place <- correct_misspellings(df$publication_place,"linkoping","Linköping")
df$publication_place <- correct_misspellings(df$publication_place,"lontoo","Lontoo")
df$publication_place <- correct_misspellings(df$publication_place,"loviisa","Loviisa")
df$publication_place <- correct_misspellings(df$publication_place,"lund","Lund")
df$publication_place <- correct_misspellings(df$publication_place,"lyypekki","Lyypekki")
df$publication_place <- correct_misspellings(df$publication_place,"maarianhamina","Maarianhamina")
df$publication_place <- correct_misspellings(df$publication_place,"magdeburg","Magdeburg")
df$publication_place <- correct_misspellings(df$publication_place,"marburg","Marburg")
df$publication_place <- correct_misspellings(df$publication_place,"mikkeli","Mikkeli")
df$publication_place <- correct_misspellings(df$publication_place,"milwaukee","Milwaukee WI")
df$publication_place <- correct_misspellings(df$publication_place,"minneapolis","Minneapolis MN")
df$publication_place <- correct_misspellings(df$publication_place,"moskova","Moskova")
df$publication_place <- correct_misspellings(df$publication_place,"nanaimo","Nanaimo BC")
df$publication_place <- correct_misspellings(df$publication_place,"narva","Narva")
df$publication_place <- correct_misspellings(df$publication_place,"newyork","New York NY")
df$publication_place <- correct_misspellings(df$publication_place,"newyorkmills","New York Mills MN")
df$publication_place <- correct_misspellings(df$publication_place,"oslo","Oslo")
df$publication_place <- correct_misspellings(df$publication_place,"oulu","Oulu")
df$publication_place <- correct_misspellings(df$publication_place,"pariisi","Pariisi")
df$publication_place <- correct_misspellings(df$publication_place,"philadelphia","Philadelphia PA")
df$publication_place <- correct_misspellings(df$publication_place,"pietari","Pietari")
df$publication_place <- correct_misspellings(df$publication_place,"pietarsaari","Pietarsaari")
df$publication_place <- correct_misspellings(df$publication_place,"pori","Pori")
df$publication_place <- correct_misspellings(df$publication_place,"portarthur","Port Arthur ON")
df$publication_place <- correct_misspellings(df$publication_place,"portland","Portland OR")
df$publication_place <- correct_misspellings(df$publication_place,"porvoo","Porvoo")
df$publication_place <- correct_misspellings(df$publication_place,"parnu","Pärnu")
df$publication_place <- correct_misspellings(df$publication_place,"quincy","Quincy MA")
df$publication_place <- correct_misspellings(df$publication_place,"rauma","Rauma")
df$publication_place <- correct_misspellings(df$publication_place,"riika","Riika")
df$publication_place <- correct_misspellings(df$publication_place,"rockisland","Rock Island IL")
df$publication_place <- correct_misspellings(df$publication_place,"rooma","Rooma")
df$publication_place <- correct_misspellings(df$publication_place,"rostock","Rostock")
df$publication_place <- correct_misspellings(df$publication_place,"seattle","Seattle WA")
df$publication_place <- correct_misspellings(df$publication_place,"sipoo","Sipoo")
df$publication_place <- correct_misspellings(df$publication_place,"smithville","Smithville MN")
df$publication_place <- correct_misspellings(df$publication_place,"sortavala","Sortavala")
df$publication_place <- correct_misspellings(df$publication_place,"strangnas","Strängnäs")
df$publication_place <- correct_misspellings(df$publication_place,"superior","Superior WI")
df$publication_place <- correct_misspellings(df$publication_place,"tallinna","Tallinna")
df$publication_place <- correct_misspellings(df$publication_place,"tammisaari","Tammisaari")
df$publication_place <- correct_misspellings(df$publication_place,"tampere","Tampere")
df$publication_place <- correct_misspellings(df$publication_place,"tartto","Tartto")
df$publication_place <- correct_misspellings(df$publication_place,"tukholma","Tukholma")
df$publication_place <- correct_misspellings(df$publication_place,"turenki","Turenki")
df$publication_place <- correct_misspellings(df$publication_place,"turku","Turku")
df$publication_place <- correct_misspellings(df$publication_place,"uppsala","Uppsala")
df$publication_place <- correct_misspellings(df$publication_place,"uusikaarlepyy","Uusikaarlepyy")
df$publication_place <- correct_misspellings(df$publication_place,"uusikaupunki","Uusikaupunki")
df$publication_place <- correct_misspellings(df$publication_place,"vaasa","Vaasa")
df$publication_place <- correct_misspellings(df$publication_place,"viipuri","Viipuri")
df$publication_place <- correct_misspellings(df$publication_place,"vasteros","Västerås")
df$publication_place <- correct_misspellings(df$publication_place,"wittenberg","Wittenberg")
df$publication_place <- correct_misspellings(df$publication_place,"worcester","Worcester MA")

#v[v=="Stockholmisa ja Turusa"] <- "Tukholma; Turku"
#v[v=="Stockholm och Åbo"] <- "Tukholma; Turku"
#v[v=="Stockholm; Helsingfors"] <- "Tukholma; Helsinki"
#v[v=="Stockholm Upsala och Åbo"] <- "Tukholma; Uppsala; Turku"
#v[v=="Kristiina"] <- "Kristiinankaupunki" # vai Ristiina
#v[v=="Pest"] <- "Budapest" # ???
#v[v=="Hernösand"] <- "Härnösand"
#v[v=="Carlscrona"] <- "Karlskrona"

#city$goteborg <- c(city$goteborg,"Gothoburgi","Gothoburgae")
#city$greifswald <- c(city$greifswald,"Gryphiae","Gryphiswaldi")
#city$helsinki <- c(city$helsinki,"Helsingforsiae","Hki","Helsingissä; Helsinki","Hfors","Helsingforsisa","Helsingfors; Helsingfors","Helsingfors Helsingi")
#city$koopenhamina <- c(city$koopenhamina,"Copenhague","Köpenhamn")
#city$leiden <- c(city$leiden,"Ludguni Batavorum")
#city$linkoping <- c(city$linkoping,"Lincopiae")
#city$lund <- c(city$lund,"Londini Goth","Lond Scanorum","Londini Scanor")
#city$marburg <- c(city$marburg,"Marpvrgi Cattorvm")
#city$pietari <- c(city$pietari,"Sanktpeterburg","Sankt Peterburg","St Pietarbori","Peterburis")
#city$porvoo <- c(city$porvoo,"Porvoo; Borgo")
#city$parnu <- c(city$parnu,"Pernaviae")
#city$riika <- c(city$riika,"Rigasa","Rijasa")
#city$rostock <- c(city$rostock,"Rostochiae")
#city$strangnas <- c(city$strangnas,"Stregnesij","Strengnesiae")
#city$tallinna <- c(city$tallinna,"Revelis","Revaliae")
#city$tartto <- c(city$tartto,"Dorpati Livonvm")
#city$tukholma <- c(city$tukholma,"Stockholmiae","Stockholmin","Stockholman","Stockholme","Holmiae","Stokholmiae","Stuckhulmisa","Stockh","Stocholmiae","Stockhomin","Tukhulmi")
#city$turku <- c(city$turku,"Abogiae")
#city$viipuri <- c(city$viipuri,"Wiburisa","Wiburgiae","Wiburis")
