source("R/placenames.R", encoding="UTF-8")

unique_cities <- unique(df$city)

# -------------------------------------------------------------------------------------------------------------------------------------------------------------

unique_cities <- collect_misspellings("almena",c("Almena","Almena WI","Almena Wis","Almena Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("altdorf",c("Altdorf"),unique_cities)
unique_cities <- collect_misspellings("ashtabula",c("Ashtabula","Ashtabula OH","Ashtabula Ohio"),unique_cities)
unique_cities <- collect_misspellings("astoria",c("Astoria","Astoria OR","Astoria Ore","Astoria Oregon"),unique_cities)
unique_cities <- collect_misspellings("berliini",c("Berliini","Berlin"),unique_cities)
unique_cities <- collect_misspellings("boston",c("Boston","Boston MA","Boston Mass","Boston Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("bridgeport",c("Bridgeport","Bridgeport CT","Bridgeport Conn","Bridgeport Connecticut"),unique_cities)
unique_cities <- collect_misspellings("bronx",c("Bronx","Bronx NY","Bronx New York"),unique_cities)
unique_cities <- collect_misspellings("brooklyn",c("Brooklyn","Brooklyn NY","Brooklyn New York"),unique_cities)
unique_cities <- collect_misspellings("calumet",c("Calumet","Calumet MI","Calumet Mich","Calumet Michigan"),unique_cities)
unique_cities <- collect_misspellings("chicago",c("Chicago","Chicago IL","Chicago Ill","Chicago Illinois"),unique_cities)
unique_cities <- collect_misspellings("chisholm",c("Chisholm","Chisholm MN","Chisholm Minn","Chisholm Minnesota"),unique_cities)
unique_cities <- collect_misspellings("cincinnati",c("Cincinnati","Cincinnati OH","Cincinnati Ohio"),unique_cities)
unique_cities <- collect_misspellings("cleveland",c("Cleveland","Cleveland OH","Cleveland Ohio"),unique_cities)
unique_cities <- collect_misspellings("duluth",c("Duluth","Duluth MN","Duluth Minn","Duluth Minnesota"),unique_cities)
unique_cities <- collect_misspellings("espoo",c("Espoo","Esbo"),unique_cities)
unique_cities <- collect_misspellings("fitchburg",c("Fitchburg","Fitchburg MA","Fitchburg Mass","Fitchburg Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("giessen",c("Giessen","Giessae","Giessae Cattorum"),unique_cities)
unique_cities <- collect_misspellings("goteborg",c("Göteborg","Gothenburg"),unique_cities)
unique_cities <- collect_misspellings("gottingen",c("Göttingen","Goettingae"),unique_cities)
unique_cities <- collect_misspellings("greifswald",c("Greifswald","Gryphiswaldae"),unique_cities)
unique_cities <- collect_misspellings("haaparanta",c("Haaparanta","Haparanda"),unique_cities)
unique_cities <- collect_misspellings("hamina",c("Hamina","Haminassa","Fredrikshamn"),unique_cities)
unique_cities <- collect_misspellings("hampuri",c("Hampuri","Hamburg"),unique_cities)
unique_cities <- collect_misspellings("hancock",c("Hancock","Hancock MI","Hancock Mich", "Hancock Michigan"),unique_cities)
unique_cities <- collect_misspellings("hanko",c("Hanko","Hangö"),unique_cities)
unique_cities <- collect_misspellings("helsinki",c("Helsinki","Helsingissä","Helsingfors"),unique_cities)
unique_cities <- collect_misspellings("hameenlinna",c("Hämeenlinna","Hämeenlinnassa","Tavastehus"),unique_cities)
unique_cities <- collect_misspellings("ironwood",c("Ironwood","Ironwood MI","Ironwood Mich","Ironwood Michigan"),unique_cities)
unique_cities <- collect_misspellings("ishpeming",c("Ishpeming","Ishpeming MI","Ishpeming Mich","Ishpeming Michigan"),unique_cities)
unique_cities <- collect_misspellings("jena",c("Jena"),unique_cities)
unique_cities <- collect_misspellings("jyvaskyla",c("Jyväskylä","Jyväskylässä"),unique_cities)
unique_cities <- collect_misspellings("kaleva",c("Kaleva","Kaleva MI","Kaleva Mich","Kaleva Michigan"),unique_cities)
unique_cities <- collect_misspellings("kaliningrad",c("Kaliningrad","Königsberg","Regiomonti Borussorum"),unique_cities)
unique_cities <- collect_misspellings("karjaa",c("Karjaa","Karis"),unique_cities)
unique_cities <- collect_misspellings("kaskinen",c("Kaskinen","Kaskö"),unique_cities)
unique_cities <- collect_misspellings("kiel",c("Kiel","Kiliae"),unique_cities)
unique_cities <- collect_misspellings("kokkola",c("Kokkola","Gamlakarleby"),unique_cities)
unique_cities <- collect_misspellings("kotka",c("Kotka","Kotkassa"),unique_cities)
unique_cities <- collect_misspellings("kouvola",c("Kouvola"),unique_cities)
unique_cities <- collect_misspellings("kristiinankaupunki",c("Kristiinankaupunki","Kristinestad"),unique_cities)
unique_cities <- collect_misspellings("kruunupyy",c("Kruunupyy","Kronoby"),unique_cities)
unique_cities <- collect_misspellings("kuopio",c("Kuopio","Kuopiossa"),unique_cities)
unique_cities <- collect_misspellings("koln",c("Köln","Cologne"),unique_cities)
unique_cities <- collect_misspellings("koopenhamina",c("Kööpenhamina","Köbenhavn","Copenhagen"),unique_cities)
unique_cities <- collect_misspellings("lappeenranta",c("Lappeenranta","Lappeenrannassa","Willmanstrand"),unique_cities)
unique_cities <- collect_misspellings("lahti",c("Lahti"),unique_cities)
unique_cities <- collect_misspellings("leiden",c("Leiden","Lugduni Batauorum","Lvgdvni Batavorvm"),unique_cities)
unique_cities <- collect_misspellings("linkoping",c("Linköping"),unique_cities)
unique_cities <- collect_misspellings("lontoo",c("Lontoo","London","Londres"),unique_cities)
unique_cities <- collect_misspellings("loviisa",c("Loviisa"),unique_cities)
unique_cities <- collect_misspellings("lund",c("Lund","Lundae","Londini Gothorum","Londini Scanorum"),unique_cities)
unique_cities <- collect_misspellings("lyypekki",c("Lyypekki","Lübeck"),unique_cities)
unique_cities <- collect_misspellings("maarianhamina",c("Maarianhamina","Mariehamn"),unique_cities)
unique_cities <- collect_misspellings("magdeburg",c("Magdeburg","Magdaeburgi"),unique_cities)
unique_cities <- collect_misspellings("marburg",c("Marburg","Marpurgi Cattorum","Marpvrgi Cattorvm"),unique_cities)
unique_cities <- collect_misspellings("mikkeli",c("Mikkeli","Mikkelissä","St Mikkeli","St Michel"),unique_cities)
unique_cities <- collect_misspellings("milwaukee",c("Milwaukee","Milwaukee WI","Milwaukee Wis","Milwaukee Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("minneapolis",c("Minneapolis","Minneapolis MN","Minneapolis Minn","Minneapolis Minneasota"),unique_cities)
unique_cities <- collect_misspellings("moskova",c("Moskova","Moskau"),unique_cities)
unique_cities <- collect_misspellings("nanaimo",c("Nanaimo","Nanaimo BC"),unique_cities)
unique_cities <- collect_misspellings("narva",c("Narva"),unique_cities)
unique_cities <- collect_misspellings("newyork",c("New York","New York NY","New York New York"),unique_cities)
unique_cities <- collect_misspellings("newyorkmills",c("New York Mills","New York Mills MN","New York Mills Minn"),unique_cities)
unique_cities <- collect_misspellings("oslo",c("Oslo","Kristiania","Christiania"),unique_cities)
unique_cities <- collect_misspellings("oulu",c("Oulu","Oulussa","Uleåborg"),unique_cities)
unique_cities <- collect_misspellings("pariisi",c("Pariisi","Paris"),unique_cities)
unique_cities <- collect_misspellings("philadelphia",c("Philadelphia","Philadelphia PA","Philadelphia Penn","Philadelphia Pennsylvania"),unique_cities)
unique_cities <- collect_misspellings("pietari",c("Pietari","Pietarissa","St Peterburg","St Petersburg","Petrograd"),unique_cities)
unique_cities <- collect_misspellings("pietarsaari",c("Pietarsaari","Jakobstad"),unique_cities)
unique_cities <- collect_misspellings("pori",c("Pori","Porissa","Björneborg"),unique_cities)
unique_cities <- collect_misspellings("portland",c("Portland","Portland OR","Portland Oregon"),unique_cities)
unique_cities <- collect_misspellings("porvoo",c("Porvoo","Porvoossa","Borgå"),unique_cities)
unique_cities <- collect_misspellings("parnu",c("Pärnu"),unique_cities)
unique_cities <- collect_misspellings("portarthur",c("Port Arthur","Port Arthur ON","Port Arthur Ont","Port Arthur Ontario"),unique_cities)
unique_cities <- collect_misspellings("quincy",c("Quincy","Quincy MA","Quincy Mass","Quincy Massachusetts"),unique_cities)
unique_cities <- collect_misspellings("rauma",c("Rauma","Raumalla"),unique_cities)
unique_cities <- collect_misspellings("riika",c("Riika","Riga"),unique_cities)
unique_cities <- collect_misspellings("rockisland",c("Rock Island","Rock Island IL","Rock Island Ill","Rock Island Illinois"),unique_cities)
unique_cities <- collect_misspellings("rooma",c("Rooma"),unique_cities)
unique_cities <- collect_misspellings("rostock",c("Rostock","Rostochii"),unique_cities)
unique_cities <- collect_misspellings("seattle",c("Seattle","Seattle WA","Seattle Wash","Seattle Washington"),unique_cities)
unique_cities <- collect_misspellings("sipoo",c("Sipoo","Sibbo"),unique_cities)
unique_cities <- collect_misspellings("smithville",c("Smithville","Smithville MN","Smithville Minn","Smithville Minnesota"),unique_cities)
unique_cities <- collect_misspellings("sortavala",c("Sortavala","Sortavalassa"),unique_cities)
unique_cities <- collect_misspellings("strangnas",c("Strängnäs"),unique_cities)
unique_cities <- collect_misspellings("superior",c("Superior","Superior WI","Superior Wis","Superior Wisconsin"),unique_cities)
unique_cities <- collect_misspellings("tallinna",c("Tallinna","Reval"),unique_cities)
unique_cities <- collect_misspellings("tammisaari",c("Tammisaari","Ekenäs"),unique_cities)
unique_cities <- collect_misspellings("tampere",c("Tampere","Tampereella","Tammerfors"),unique_cities)
unique_cities <- collect_misspellings("tartto",c("Tartto","Tartu","Dorpati","Dorpati Livonorum"),unique_cities)
unique_cities <- collect_misspellings("tukholma",c("Tukholma","Tukholmassa","Stockholm"),unique_cities)
unique_cities <- collect_misspellings("turenki",c("Turenki"),unique_cities)
unique_cities <- collect_misspellings("turku",c("Turku","Turussa","Åbo","Aboae","Aboae Finnorum"),unique_cities)
unique_cities <- collect_misspellings("uppsala",c("Uppsala","Uppsalassa"),unique_cities)
unique_cities <- collect_misspellings("uusikaarlepyy",c("Uusikaarlepyy","Nykarleby"),unique_cities)
unique_cities <- collect_misspellings("uusikaupunki",c("Uusikaupunki","Nystad"),unique_cities)
unique_cities <- collect_misspellings("vaasa",c("Vaasa","Vaasassa","Nikolainkaupunki","Nikolainkaupungissa","Nikolaistad"),unique_cities)
unique_cities <- collect_misspellings("viipuri",c("Viipuri","Viipurissa","Viborg"),unique_cities) # huom! Tanskassakin on Viborg
unique_cities <- collect_misspellings("vasteros",c("Västerås","Arosia","Arosiensis","Westrosia"),unique_cities)
unique_cities <- collect_misspellings("wittenberg",c("Wittenberg","Wittenbergae"),unique_cities)
unique_cities <- collect_misspellings("worcester",c("Worcester","Worcester MA","Worcester Mass","Worcester Massachusetts"),unique_cities)

write(unique_cities, file="inst/examples/output.tables/city_others.csv")

# -------------------------------------------------------------------------------------------------------------------------------------------------------------

df$city <- correct_misspellings(df$city,"almena","Almena WI")
df$city <- correct_misspellings(df$city,"altdorf","Altdorf")
df$city <- correct_misspellings(df$city,"ashtabula","Ashtabula OH")
df$city <- correct_misspellings(df$city,"astoria","Astoria OR")
df$city <- correct_misspellings(df$city,"berliini","Berliini")
df$city <- correct_misspellings(df$city,"boston","Boston MA")
df$city <- correct_misspellings(df$city,"bridgeport","Bridgeport CT")
df$city <- correct_misspellings(df$city,"bronx","Bronx NY")
df$city <- correct_misspellings(df$city,"brooklyn","Brooklyn NY")
df$city <- correct_misspellings(df$city,"calumet","Calumet MI")
df$city <- correct_misspellings(df$city,"chicago","Chicago IL")
df$city <- correct_misspellings(df$city,"chisholm","Chisholm MN")
df$city <- correct_misspellings(df$city,"cincinnati","Cincinnati OH")
df$city <- correct_misspellings(df$city,"cleveland","Cleveland OH")
df$city <- correct_misspellings(df$city,"duluth","Duluth MN")
df$city <- correct_misspellings(df$city,"espoo","Espoo")
df$city <- correct_misspellings(df$city,"fitchburg","Fitchburg MA")
df$city <- correct_misspellings(df$city,"giessen","Giessen")
df$city <- correct_misspellings(df$city,"goteborg","Göteborg")
df$city <- correct_misspellings(df$city,"gottingen","Göttingen")
df$city <- correct_misspellings(df$city,"greifswald","Greifswald")
df$city <- correct_misspellings(df$city,"haaparanta","Haaparanta")
df$city <- correct_misspellings(df$city,"hamina","Hamina")
df$city <- correct_misspellings(df$city,"hampuri","Hampuri")
df$city <- correct_misspellings(df$city,"hancock","Hancock MI")
df$city <- correct_misspellings(df$city,"hanko","Hanko")
df$city <- correct_misspellings(df$city,"helsinki","Helsinki")
df$city <- correct_misspellings(df$city,"hameenlinna","Hämeenlinna")
df$city <- correct_misspellings(df$city,"ironwood","Ironwood MI")
df$city <- correct_misspellings(df$city,"ishpeming","Ishpeming MI")
df$city <- correct_misspellings(df$city,"jena","Jena")
df$city <- correct_misspellings(df$city,"jyvaskyla","Jyväskylä")
df$city <- correct_misspellings(df$city,"kaleva","Kaleva MI")
df$city <- correct_misspellings(df$city,"kaliningrad","Kaliningrad")
df$city <- correct_misspellings(df$city,"karjaa","Karjaa")
df$city <- correct_misspellings(df$city,"kaskinen","Kaskinen")
df$city <- correct_misspellings(df$city,"kiel","Kiel")
df$city <- correct_misspellings(df$city,"kokkola","Kokkola")
df$city <- correct_misspellings(df$city,"kotka","Kotka")
df$city <- correct_misspellings(df$city,"kouvola","Kouvola")
df$city <- correct_misspellings(df$city,"kristiinankaupunki","Kristiinankaupunki")
df$city <- correct_misspellings(df$city,"kruunupyy","Kruunupyy")
df$city <- correct_misspellings(df$city,"kuopio","Kuopio")
df$city <- correct_misspellings(df$city,"koln","Köln")
df$city <- correct_misspellings(df$city,"koopenhamina","Kööpenhamina")
df$city <- correct_misspellings(df$city,"lahti","Lahti")
df$city <- correct_misspellings(df$city,"lappeenranta","Lappeenranta")
df$city <- correct_misspellings(df$city,"leiden","Leiden")
df$city <- correct_misspellings(df$city,"linkoping","Linköping")
df$city <- correct_misspellings(df$city,"lontoo","Lontoo")
df$city <- correct_misspellings(df$city,"loviisa","Loviisa")
df$city <- correct_misspellings(df$city,"lund","Lund")
df$city <- correct_misspellings(df$city,"lyypekki","Lyypekki")
df$city <- correct_misspellings(df$city,"maarianhamina","Maarianhamina")
df$city <- correct_misspellings(df$city,"magdeburg","Magdeburg")
df$city <- correct_misspellings(df$city,"marburg","Marburg")
df$city <- correct_misspellings(df$city,"mikkeli","Mikkeli")
df$city <- correct_misspellings(df$city,"milwaukee","Milwaukee WI")
df$city <- correct_misspellings(df$city,"minneapolis","Minneapolis MN")
df$city <- correct_misspellings(df$city,"moskova","Moskova")
df$city <- correct_misspellings(df$city,"nanaimo","Nanaimo BC")
df$city <- correct_misspellings(df$city,"narva","Narva")
df$city <- correct_misspellings(df$city,"newyork","New York NY")
df$city <- correct_misspellings(df$city,"newyorkmills","New York Mills MN")
df$city <- correct_misspellings(df$city,"oslo","Oslo")
df$city <- correct_misspellings(df$city,"oulu","Oulu")
df$city <- correct_misspellings(df$city,"pariisi","Pariisi")
df$city <- correct_misspellings(df$city,"philadelphia","Philadelphia PA")
df$city <- correct_misspellings(df$city,"pietari","Pietari")
df$city <- correct_misspellings(df$city,"pietarsaari","Pietarsaari")
df$city <- correct_misspellings(df$city,"pori","Pori")
df$city <- correct_misspellings(df$city,"portarthur","Port Arthur ON")
df$city <- correct_misspellings(df$city,"portland","Portland OR")
df$city <- correct_misspellings(df$city,"porvoo","Porvoo")
df$city <- correct_misspellings(df$city,"parnu","Pärnu")
df$city <- correct_misspellings(df$city,"quincy","Quincy MA")
df$city <- correct_misspellings(df$city,"rauma","Rauma")
df$city <- correct_misspellings(df$city,"riika","Riika")
df$city <- correct_misspellings(df$city,"rockisland","Rock Island IL")
df$city <- correct_misspellings(df$city,"rooma","Rooma")
df$city <- correct_misspellings(df$city,"rostock","Rostock")
df$city <- correct_misspellings(df$city,"seattle","Seattle WA")
df$city <- correct_misspellings(df$city,"sipoo","Sipoo")
df$city <- correct_misspellings(df$city,"smithville","Smithville MN")
df$city <- correct_misspellings(df$city,"sortavala","Sortavala")
df$city <- correct_misspellings(df$city,"strangnas","Strängnäs")
df$city <- correct_misspellings(df$city,"superior","Superior WI")
df$city <- correct_misspellings(df$city,"tallinna","Tallinna")
df$city <- correct_misspellings(df$city,"tammisaari","Tammisaari")
df$city <- correct_misspellings(df$city,"tampere","Tampere")
df$city <- correct_misspellings(df$city,"tartto","Tartto")
df$city <- correct_misspellings(df$city,"tukholma","Tukholma")
df$city <- correct_misspellings(df$city,"turenki","Turenki")
df$city <- correct_misspellings(df$city,"turku","Turku")
df$city <- correct_misspellings(df$city,"uppsala","Uppsala")
df$city <- correct_misspellings(df$city,"uusikaarlepyy","Uusikaarlepyy")
df$city <- correct_misspellings(df$city,"uusikaupunki","Uusikaupunki")
df$city <- correct_misspellings(df$city,"vaasa","Vaasa")
df$city <- correct_misspellings(df$city,"viipuri","Viipuri")
df$city <- correct_misspellings(df$city,"vasteros","Västerås")
df$city <- correct_misspellings(df$city,"wittenberg","Wittenberg")
df$city <- correct_misspellings(df$city,"worcester","Worcester MA")

#v[v=="Stockholmisa ja Turusa"] <- "Tukholma; Turku"
#v[v=="Stockholm och Åbo"] <- "Tukholma; Turku"
#v[v=="Stockholm; Helsingfors"] <- "Tukholma; Helsinki"
#v[v=="Stockholm Upsala och Åbo"] <- "Tukholma; Uppsala; Turku"
#v[v=="Kristiina"] <- "Kristiinankaupunki" # vai Ristiina
#v[v=="Pest"] <- "Budapest" # ???
#v[v=="Hernösand"] <- "Härnösand"
#v[v=="Carlscrona"] <- "Karlskrona"

#city$goteborg <- c(city$goteborg,"Gothoburgi","Gothoburgae")
#city$greifswald <- c(city$greifswald,"Gryphiae","Gryphiswaldi")
#city$helsinki <- c(city$helsinki,"Helsingforsiae","Hki","Helsingissä; Helsinki","Hfors","Helsingforsisa","Helsingfors; Helsingfors","Helsingfors Helsingi")
#city$koopenhamina <- c(city$koopenhamina,"Copenhague","Köpenhamn")
#city$leiden <- c(city$leiden,"Ludguni Batavorum")
#city$linkoping <- c(city$linkoping,"Lincopiae")
#city$lund <- c(city$lund,"Londini Goth","Lond Scanorum","Londini Scanor")
#city$marburg <- c(city$marburg,"Marpvrgi Cattorvm")
#city$pietari <- c(city$pietari,"Sanktpeterburg","Sankt Peterburg","St Pietarbori","Peterburis")
#city$porvoo <- c(city$porvoo,"Porvoo; Borgo")
#city$parnu <- c(city$parnu,"Pernaviae")
#city$riika <- c(city$riika,"Rigasa","Rijasa")
#city$rostock <- c(city$rostock,"Rostochiae")
#city$strangnas <- c(city$strangnas,"Stregnesij","Strengnesiae")
#city$tallinna <- c(city$tallinna,"Revelis","Revaliae")
#city$tartto <- c(city$tartto,"Dorpati Livonvm")
#city$tukholma <- c(city$tukholma,"Stockholmiae","Stockholmin","Stockholman","Stockholme","Holmiae","Stokholmiae","Stuckhulmisa","Stockh","Stocholmiae","Stockhomin","Tukhulmi")
#city$turku <- c(city$turku,"Abogiae")
#city$viipuri <- c(city$viipuri,"Wiburisa","Wiburgiae","Wiburis")
