collect_misspellings <- function (v,w) {
	eff <- 1
	while (eff > 0) {
		eff <- 0
		for (i in 1:length(v)) {
			if(is.na(v[i])) {
				next
			}
			if(min(adist(v[i],w)) == 1){
				w <- c(w,v[i])
				eff <- 1
			}
		}
	}
	w
}

city <- new.env()

city$almena <- collect_misspellings(df$pub_where,c("Almena","Almena WI","Almena Wis","Almena Wisconsin"))
city$altdorf <- collect_misspellings(df$pub_where,c("Altdorf"))
city$ashtabula <- collect_misspellings(df$pub_where,c("Ashtabula","Ashtabula OH","Ashtabula Ohio"))
city$astoria <- collect_misspellings(df$pub_where,c("Astoria","Astoria OR","Astoria Ore","Astoria Oregon"))
city$berliini <- collect_misspellings(df$pub_where,c("Berliini","Berlin"))
city$boston <- collect_misspellings(df$pub_where,c("Boston","Boston MA","Boston Mass","Boston Massachusetts"))
city$bridgeport <- collect_misspellings(df$pub_where,c("Bridgeport","Bridgeport CT","Bridgeport Conn","Bridgeport Connecticut"))
city$bronx <- collect_misspellings(df$pub_where,c("Bronx","Bronx NY","Bronx New York"))
city$brooklyn <- collect_misspellings(df$pub_where,c("Brooklyn","Brooklyn NY","Brooklyn New York"))
city$calumet <- collect_misspellings(df$pub_where,c("Calumet","Calumet MI","Calumet Mich","Calumet Michigan"))
city$chicago <- collect_misspellings(df$pub_where,c("Chicago","Chicago IL","Chicago Ill","Chicago Illinois"))
city$chisholm <- collect_misspellings(df$pub_where,c("Chisholm","Chisholm MN","Chisholm Minn","Chisholm Minnesota"))
city$cincinnati <- collect_misspellings(df$pub_where,c("Cincinnati","Cincinnati OH","Cincinnati Ohio"))
city$cleveland <- collect_misspellings(df$pub_where,c("Cleveland","Cleveland OH","Cleveland Ohio"))
city$duluth <- collect_misspellings(df$pub_where,c("Duluth","Duluth MN","Duluth Minn","Duluth Minnesota"))
city$espoo <- collect_misspellings(df$pub_where,c("Espoo","Esbo"))
city$fitchburg <- collect_misspellings(df$pub_where,c("Fitchburg","Fitchburg MA","Fitchburg Mass","Fitchburg Massachusetts"))
city$giessen <- collect_misspellings(df$pub_where,c("Giessen","Giessae","Giessae Cattorum"))
city$goteborg <- collect_misspellings(df$pub_where,c("Göteborg","Gothenburg"))
city$gottingen <- collect_misspellings(df$pub_where,c("Göttingen","Goettingae"))
city$greifswald <- collect_misspellings(df$pub_where,c("Greifswald","Gryphiswaldae"))
city$haaparanta <- collect_misspellings(df$pub_where,c("Haaparanta","Haparanda"))
city$hamina <- collect_misspellings(df$pub_where,c("Hamina","Haminassa","Fredrikshamn"))
city$hampuri <- collect_misspellings(df$pub_where,c("Hampuri","Hamburg"))
city$hancock <- collect_misspellings(df$pub_where,c("Hancock","Hancock MI","Hancock Mich", "Hancock Michigan"))
city$hanko <- collect_misspellings(df$pub_where,c("Hanko","Hangö"))
city$helsinki <- collect_misspellings(df$pub_where,c("Helsinki","Helsingissä","Helsingfors"))
city$hameenlinna <- collect_misspellings(df$pub_where,c("Hämeenlinna","Hämeenlinnassa","Tavastehus"))
city$ironwood <- collect_misspellings(df$pub_where,c("Ironwood","Ironwood MI","Ironwood Mich","Ironwood Michigan"))
city$ishpeming <- collect_misspellings(df$pub_where,c("Ishpeming","Ishpeming MI","Ishpeming Mich","Ishpeming Michigan"))
city$jena <- collect_misspellings(df$pub_where,c("Jena"))
city$jyvaskyla <- collect_misspellings(df$pub_where,c("Jyväskylä","Jyväskylässä"))
city$kaleva <- collect_misspellings(df$pub_where,c("Kaleva","Kaleva MI","Kaleva Mich","Kaleva Michigan"))
city$kaliningrad <- collect_misspellings(df$pub_where,c("Kaliningrad","Königsberg","Regiomonti Borussorum"))
city$karjaa <- collect_misspellings(df$pub_where,c("Karjaa","Karis"))
city$kaskinen <- collect_misspellings(df$pub_where,c("Kaskinen","Kaskö"))
city$kiel <- collect_misspellings(df$pub_where,c("Kiel","Kiliae"))
city$kokkola <- collect_misspellings(df$pub_where,c("Kokkola","Gamlakarleby"))
city$kotka <- collect_misspellings(df$pub_where,c("Kotka","Kotkassa"))
city$kouvola <- collect_misspellings(df$pub_where,c("Kouvola"))
city$kristiinankaupunki <- collect_misspellings(df$pub_where,c("Kristiinankaupunki","Kristinestad"))
city$kruunupyy <- collect_misspellings(df$pub_where,c("Kruunupyy","Kronoby"))
city$kuopio <- collect_misspellings(df$pub_where,c("Kuopio","Kuopiossa"))
city$koln <- collect_misspellings(df$pub_where,c("Köln","Cologne"))
city$koopenhamina <- collect_misspellings(df$pub_where,c("Kööpenhamina","Köbenhavn","Copenhagen"))
city$lappeenranta <- collect_misspellings(df$pub_where,c("Lappeenranta","Lappeenrannassa","Willmanstrand"))
city$lahti <- collect_misspellings(df$pub_where,c("Lahti"))
city$leiden <- collect_misspellings(df$pub_where,c("Leiden","Lugduni Batauorum","Lvgdvni Batavorvm"))
city$linkoping <- collect_misspellings(df$pub_where,c("Linköping"))
city$lontoo <- collect_misspellings(df$pub_where,c("Lontoo","London","Londres"))
city$loviisa <- collect_misspellings(df$pub_where,c("Loviisa"))
city$lund <- collect_misspellings(df$pub_where,c("Lund","Lundae","Londini Gothorum","Londini Scanorum"))
city$lyypekki <- collect_misspellings(df$pub_where,c("Lyypekki","Lübeck"))
city$maarianhamina <- collect_misspellings(df$pub_where,c("Maarianhamina","Mariehamn"))
city$magdeburg <- collect_misspellings(df$pub_where,c("Magdeburg","Magdaeburgi"))
city$marburg <- collect_misspellings(df$pub_where,c("Marburg","Marpurgi Cattorum","Marpvrgi Cattorvm"))
city$mikkeli <- collect_misspellings(df$pub_where,c("Mikkeli","Mikkelissä","St Mikkeli","St Michel"))
city$milwaukee <- collect_misspellings(df$pub_where,c("Milwaukee","Milwaukee WI","Milwaukee Wis","Milwaukee Wisconsin"))
city$minneapolis <- collect_misspellings(df$pub_where,c("Minneapolis","Minneapolis MN","Minneapolis Minn","Minneapolis Minneasota"))
city$moskova <- collect_misspellings(df$pub_where,c("Moskova","Moskau"))
city$nanaimo <- collect_misspellings(df$pub_where,c("Nanaimo","Nanaimo BC"))
city$narva <- collect_misspellings(df$pub_where,c("Narva"))
city$newyork <- collect_misspellings(df$pub_where,c("New York","New York NY","New York New York"))
city$newyorkmills <- collect_misspellings(df$pub_where,c("New York Mills","New York Mills MN","New York Mills Minn"))
city$oslo <- collect_misspellings(df$pub_where,c("Oslo","Kristiania","Christiania"))
city$oulu <- collect_misspellings(df$pub_where,c("Oulu","Oulussa","Uleåborg"))
city$pariisi <- collect_misspellings(df$pub_where,c("Pariisi","Paris"))
city$philadelphia <- collect_misspellings(df$pub_where,c("Philadelphia","Philadelphia PA","Philadelphia Penn","Philadelphia Pennsylvania"))
city$pietari <- collect_misspellings(df$pub_where,c("Pietari","Pietarissa","St Petersburg","Petrograd"))
city$pietarsaari <- collect_misspellings(df$pub_where,c("Pietarsaari","Jakobstad"))
city$pori <- collect_misspellings(df$pub_where,c("Pori","Porissa","Björneborg"))
city$portland <- collect_misspellings(df$pub_where,c("Portland","Portland OR","Portland Oregon"))
city$porvoo <- collect_misspellings(df$pub_where,c("Porvoo","Porvoossa","Borgå"))
city$parnu <- collect_misspellings(df$pub_where,c("Pärnu"))
city$portarthur <- collect_misspellings(df$pub_where,c("Port Arthur","Port Arthur ON","Port Arthur Ont","Port Arthur Ontario"))
city$quincy <- collect_misspellings(df$pub_where,c("Quincy","Quincy MA","Quincy Mass","Quincy Massachusetts"))
city$rauma <- collect_misspellings(df$pub_where,c("Rauma","Raumalla"))
city$riika <- collect_misspellings(df$pub_where,c("Riika","Riga"))
city$rockisland <- collect_misspellings(df$pub_where,c("Rock Island","Rock Island IL","Rock Island Ill","Rock Island Illinois"))
city$rooma <- collect_misspellings(df$pub_where,c("Rooma"))
city$rostock <- collect_misspellings(df$pub_where,c("Rostock","Rostochii"))
city$seattle <- collect_misspellings(df$pub_where,c("Seattle","Seattle WA","Seattle Wash","Seattle Washington"))
city$sipoo <- collect_misspellings(df$pub_where,c("Sipoo","Sibbo"))
city$smithville <- collect_misspellings(df$pub_where,c("Smithville","Smithville MN","Smithville Minn","Smithville Minnesota"))
city$sortavala <- collect_misspellings(df$pub_where,c("Sortavala","Sortavalassa"))
city$strangnas <- collect_misspellings(df$pub_where,c("Strängnäs"))
city$superior <- collect_misspellings(df$pub_where,c("Superior","Superior WI","Superior Wis","Superior Wisconsin"))
city$tallinna <- collect_misspellings(df$pub_where,c("Tallinna","Reval"))
city$tammisaari <- collect_misspellings(df$pub_where,c("Tammisaari","Ekenäs"))
city$tampere <- collect_misspellings(df$pub_where,c("Tampere","Tampereella","Tammerfors"))
city$tartto <- collect_misspellings(df$pub_where,c("Tartto","Tartu","Dorpati","Dorpati Livonorum"))
city$tukholma <- collect_misspellings(df$pub_where,c("Tukholma","Tukholmassa","Stockholm"))
city$turenki <- collect_misspellings(df$pub_where,c("Turenki"))
city$turku <- collect_misspellings(df$pub_where,c("Turku","Turussa","Åbo","Aboae","Aboae Finnorum"))
city$uppsala <- collect_misspellings(df$pub_where,c("Uppsala"))
city$uusikaarlepyy <- collect_misspellings(df$pub_where,c("Uusikaarlepyy","Nykarleby"))
city$uusikaupunki <- collect_misspellings(df$pub_where,c("Uusikaupunki","Nystad"))
city$vaasa <- collect_misspellings(df$pub_where,c("Vaasa","Nikolainkaupunki","Nikolainkaupungissa","Nikolaistad"))
city$viipuri <- collect_misspellings(df$pub_where,c("Viipuri","Viipurissa","Viborg")) # huom! Tanskassakin on Viborg
city$vasteros <- collect_misspellings(df$pub_where,c("Västerås","Arosia","Arosiensis","Westrosia"))
city$wittenberg <- collect_misspellings(df$pub_where,c("Wittenberg","Wittenbergae"))
city$worcester <- collect_misspellings(df$pub_where,c("Worcester","Worcester MA","Worcester Mass","Worcester Massachusetts"))

city$goteborg <- c(city$goteborg,"Gothoburgi","Gothoburgae")
city$greifswald <- c(city$greifswald,"Gryphiae","Gryphiswaldi")
city$helsinki <- c(city$helsinki,"Helsingforsiae","Hki","Helsingissä; Helsinki","Hfors","Helsingforsisa","Helsingfors; Helsingfors","Helsingfors Helsingi")
city$koopenhamina <- c(city$koopenhamina,"Copenhague","Köpenhamn")
city$leiden <- c(city$leiden,"Ludguni Batavorum")
city$linkoping <- c(city$linkoping,"Lincopiae")
city$lund <- c(city$lund,"Londini Goth","Lond Scanorum","Londini Scanor")
city$marburg <- c(city$marburg,"Marpvrgi Cattorvm")
city$pietari <- c(city$pietari,"Sanktpeterburg","Sankt Peterburg","St Pietarbori","Peterburis")
city$porvoo <- c(city$porvoo,"Porvoo; Borgo")
city$parnu <- c(city$parnu,"Pernaviae")
city$riika <- c(city$riika,"Rigasa","Rijasa")
city$rostock <- c(city$rostock,"Rostochiae")
city$strangnas <- c(city$strangnas,"Stregnesij","Strengnesiae")
city$tallinna <- c(city$tallinna,"Revelis","Revaliae")
city$tartto <- c(city$tartto,"Dorpati Livonvm")
city$tukholma <- c(city$tukholma,"Stockholmiae","Stockholmin","Stockholman","Stockholme","Holmiae","Stokholmiae","Stuckhulmisa","Stockh","Stocholmiae","Stockhomin","Tukhulmi")
city$turku <- c(city$turku,"Abogiae")
city$viipuri <- c(city$viipuri,"Wiburisa","Wiburgiae","Wiburis")
