collect_misspellings <- function (v,w) {
	eff <- 1
	while (eff > 0) {
		eff <- 0
		for (i in 1:length(v)) {
			if(is.na(v[i])) {
				next
			}
			if(min(adist(v[i],w)) == 1){
				w <- c(w,v[i])
				eff <- 1
			}
		}
	}
	w
}

altdorf <- collect_misspellings(df$pub_where,c("Altdorf"))
ashtabula <- collect_misspellings(df$pub_where,c("Ashtabula","Ashtabula OH","Ashtabula Ohio"))
astoria <- collect_misspellings(df$pub_where,c("Astoria","Astoria OR","Astoria Ore"))
berliini <- collect_misspellings(df$pub_where,c("Berliini","Berlin"))
brooklyn <- collect_misspellings(df$pub_where,c("Brooklyn","Brooklyn NY"))
calumet <- collect_misspellings(df$pub_where,c("Calumet","Calumet MI","Calumet Mich"))
duluth <- collect_misspellings(df$pub_where,c("Duluth","Duluth MN","Duluth Minn"))
espoo <- collect_misspellings(df$pub_where,c("Espoo","Esbo"))
fitchburg <- collect_misspellings(df$pub_where,c("Fitchburg","Fitchburg MA","Fitchburg Mass"))
giessen <- collect_misspellings(df$pub_where,c("Giessen","Giessae","Giessae Cattorum"))
goteborg <- collect_misspellings(df$pub_where,c("Göteborg","Gothenburg"))
gottingen <- collect_misspellings(df$pub_where,c("Göttingen","Goettingae"))
greifswald <- collect_misspellings(df$pub_where,c("Greifswald"))
haaparanta <- collect_misspellings(df$pub_where,c("Haaparanta","Haparanda"))
hamina <- collect_misspellings(df$pub_where,c("Hamina","Fredrikshamn"))
hampuri <- collect_misspellings(df$pub_where,c("Hampuri","Hamburg"))
hancock <- collect_misspellings(df$pub_where,c("Hancock","Hancock MI","Hancock Mich"))
hanko <- collect_misspellings(df$pub_where,c("Hanko","Hangö"))
helsinki <- collect_misspellings(df$pub_where,c("Helsinki","Helsingissä","Helsingfors"))
hameenlinna <- collect_misspellings(df$pub_where,c("Hämeenlinna","Hämeenlinnassa","Tavastehus"))
jena <- collect_misspellings(df$pub_where,c("Jena"))
jyvaskyla <- collect_misspellings(df$pub_where,c("Jyväskylä","Jyväskylässä"))
kaleva <- collect_misspellings(df$pub_where,c("Kaleva","Kaleva MI","Kaleva Mich"))
kaliningrad <- collect_misspellings(df$pub_where,c("Kaliningrad","Königsberg","Regiomonti Borussorum"))
karjaa <- collect_misspellings(df$pub_where,c("Karjaa","Karis"))
kaskinen <- collect_misspellings(df$pub_where,c("Kaskinen","Kaskö"))
kiel <- collect_misspellings(df$pub_where,c("Kiel","Kiliae"))
kokkola <- collect_misspellings(df$pub_where,c("Kokkola","Gamlakarleby"))
kristiinankaupunki <- collect_misspellings(df$pub_where,c("Kristiinankaupunki","Kristinestad"))
kruunupyy <- collect_misspellings(df$pub_where,c("Kruunupyy","Kronoby"))
kuopio <- collect_misspellings(df$pub_where,c("Kuopio","Kuopiossa"))
koln <- collect_misspellings(df$pub_where,c("Köln","Cologne"))
koopenhamina <- collect_misspellings(df$pub_where,c("Kööpenhamina","Köbenhavn","Copenhagen"))
lappeenranta <- collect_misspellings(df$pub_where,c("Lappeenranta","Lappeenrannassa","Willmanstrand"))
leiden <- collect_misspellings(df$pub_where,c("Leiden","Lugduni Batauorum"))
linkoping <- collect_misspellings(df$pub_where,c("Linköping"))
lontoo <- collect_misspellings(df$pub_where,c("Lontoo","London"))
loviisa <- collect_misspellings(df$pub_where,c("Loviisa"))
lund <- collect_misspellings(df$pub_where,c("Lund"))
maarianhamina <- collect_misspellings(df$pub_where,c("Maarianhamina","Mariehamn"))
magdeburg <- collect_misspellings(df$pub_where,c("Magdeburg","Magdaeburgi"))
marburg <- collect_misspellings(df$pub_where,c("Marburg","Marpurgi Cattorum"))
mikkeli <- collect_misspellings(df$pub_where,c("Mikkeli","Mikkelissä","St Mikkeli","St Michel"))
moskova <- collect_misspellings(df$pub_where,c("Moskova","Moskau"))
narva <- collect_misspellings(df$pub_where,c("Narva"))
newyork <- collect_misspellings(df$pub_where,c("New York","New York NY"))
oslo <- collect_misspellings(df$pub_where,c("Oslo","Kristiania"))
oulu <- collect_misspellings(df$pub_where,c("Oulu","Oulussa","Uleåborg"))
pariisi <- collect_misspellings(df$pub_where,c("Pariisi","Paris"))
pietari <- collect_misspellings(df$pub_where,c("Pietari","Pietarissa","St Petersburg","Petrograd"))
pietarsaari <- collect_misspellings(df$pub_where,c("Pietarsaari","Jakobstad"))
pori <- collect_misspellings(df$pub_where,c("Pori","Björneborg"))
porvoo <- collect_misspellings(df$pub_where,c("Porvoo","Porvoossa","Borgå"))
parnu <- collect_misspellings(df$pub_where,c("Pärnu"))
riika <- collect_misspellings(df$pub_where,c("Riika","Riga"))
rooma <- collect_misspellings(df$pub_where,c("Rooma"))
rostock <- collect_misspellings(df$pub_where,c("Rostock","Rostochii"))
sipoo <- collect_misspellings(df$pub_where,c("Sipoo","Sibbo"))
sortavala <- collect_misspellings(df$pub_where,c("Sortavala","Sortavalassa"))
strangnas <- collect_misspellings(df$pub_where,c("Strängnäs"))
tallinna <- collect_misspellings(df$pub_where,c("Tallinna"))
tammisaari <- collect_misspellings(df$pub_where,c("Tammisaari","Ekenäs"))
tampere <- collect_misspellings(df$pub_where,c("Tampere","Tampereella","Tammerfors"))
tartto <- collect_misspellings(df$pub_where,c("Tartto","Tartu","Dorpati","Dorpati Livonorum"))
tukholma <- collect_misspellings(df$pub_where,c("Tukholma","Tukholmassa","Stockholm"))
turenki <- collect_misspellings(df$pub_where,c("Turenki"))
turku <- collect_misspellings(df$pub_where,c("Turku","Turussa","Åbo"))
uppsala <- collect_misspellings(df$pub_where,c("Uppsala"))
uusikaarlepyy <- collect_misspellings(df$pub_where,c("Uusikaarlepyy","Nykarleby"))
uusikaupunki <- collect_misspellings(df$pub_where,c("Uusikaupunki","Nystad"))
vaasa <- collect_misspellings(df$pub_where,c("Vaasa","Nikolainkaupunki","Nikolainkaupungissa","Nikolaistad"))
viipuri <- collect_misspellings(df$pub_where,c("Viipuri","Viipurissa","Viborg")) # huom! Tanskassakin on Viborg
wittenberg <- collect_misspellings(df$pub_where,c("Wittenberg"))

goteborg <- c(goteborg, "Gothoburgi","Gothoburgae")
greifswald <- c(greifswald, "Gryphiswaldiae","Gryphiae","Gryphiswaldi")
helsinki <- c(helsinki,"Helsingforsiae","Hki","Helsingissä; Helsinki","Hfors","Helsingforsisa","Helsingfors; Helsingfors","Helsingfors Helsingi")
koopenhamina <- c(koopenhamina,"Copenhague","Köpenhamn")
leiden <- c(leiden,"Ludguni Batavorum")
linkoping <- c(linkoping,"Lincopiae")
lund <- c(lund,"Lundae","Londini Gothorum","Londini Goth","Lond Scanorum","Londini Scanor","Londini Scanorum")
marburg <- c(marburg,"Marpvrgi Cattorvm")
pietari <- c(pietari,"Sanktpeterburg","Sankt Peterburg","St Pietarbori")
porvoo <- c(porvoo,"Porvoo; Borgo")
parnu <- c(parnu,"Pernaviae")
riika <- c(riika,"Rigasa","Rijasa")
rostock <- c(rostock,"Rostochiae")
strangnas <- c(strangnas,"Stregnesij","Strengnesiae")
tallinna <- c(tallinna,"Revelis")
tartto <- c(tartto,"Dorpati Livonvm")
tukholma <- c(tukholma,"Stockholmiae","Stockholmin","Stockholman","Stockholme","Holmiae","Stokholmiae","Stuckhulmisa","Stockh","Stocholmiae","Stockhomin","Tukhulmi")
turku <- c(turku,"Abogiae","Aboae Finnorum")
viipuri <- c(viipuri,"Wiburisa","Wiburgiae","Wiburis")
wittenberg <- c(wittenberg,"Wittebergae","Witebergae","Wittenbergae","Vitembergae")
