correct_misspellings <- function(v) {
	v[v %in% altdorf] <- "Altdorf"
	v[v %in% ashtabula] <- "Ashtabula OH"
	v[v %in% astoria] <- "Astoria OR"
	v[v %in% berliini] <- "Berliini"
	v[v %in% brooklyn] <- "Brooklyn"
	v[v %in% calumet] <- "Calumet MI"
	v[v %in% duluth] <- "Duluth"
	v[v %in% espoo] <- "Espoo"
	v[v %in% fitchburg] <- "Fitchburg MA"
	v[v %in% giessen] <- "Giessen"
	v[v %in% goteborg] <- "Göteborg"
	v[v %in% gottingen] <- "Göttingen"
	v[v %in% greifswald] <- "Greifswald"
	v[v %in% haaparanta] <- "Haaparanta"
	v[v %in% hamina] <- "Hamina"
	v[v %in% hampuri] <- "Hampuri"
	v[v %in% hancock] <- "Hancock MI"
	v[v %in% hanko] <- "Hanko"
	v[v %in% helsinki] <- "Helsinki"
	v[v %in% hameenlinna] <- "Hämeenlinna"
	v[v %in% jena] <- "Jena"
	v[v %in% jyvaskyla] <- "Jyväskylä"
	v[v %in% kaleva] <- "Kaleva MI"
	v[v %in% kaliningrad] <- "Kaliningrad"
	v[v %in% karjaa] <- "Karjaa"
	v[v %in% kaskinen] <- "Kaskinen"
	v[v %in% kiel] <- "Kiel"
	v[v %in% kokkola] <- "Kokkola"
	v[v %in% kristiinankaupunki] <- "Kristiinankaupunki"
	v[v %in% kruunupyy] <- "Kruunupyy"
	v[v %in% kuopio] <- "Kuopio"
	v[v %in% koln] <- "Köln"
	v[v %in% koopenhamina] <- "Kööpenhamina"
	v[v %in% lappeenranta] <- "Lappeenranta"
	v[v %in% leiden] <- "Leiden"
	v[v %in% linkoping] <- "Linköping"
	v[v %in% lontoo] <- "Lontoo"
	v[v %in% loviisa] <- "Loviisa"
	v[v %in% lund] <- "Lund"
	v[v %in% maarianhamina] <- "Maarianhamina"
	v[v %in% magdeburg] <- "Magdeburg"
	v[v %in% marburg] <- "Marburg"
	v[v %in% mikkeli] <- "Mikkeli"
	v[v %in% moskova] <- "Moskova"
	v[v %in% narva] <- "Narva"
	v[v %in% newyork] <- "New York NY"
	v[v %in% oslo] <- "Oslo"
	v[v %in% oulu] <- "Oulu"
	v[v %in% pariisi] <- "Pariisi"
	v[v %in% pietari] <- "Pietari"
	v[v %in% pietarsaari] <- "Pietarsaari"
	v[v %in% pori] <- "Pori"
	v[v %in% porvoo] <- "Porvoo"
	v[v %in% parnu] <- "Pärnu"
	v[v %in% riika] <- "Riika"
	v[v %in% rooma] <- "Rooma"
	v[v %in% rostock] <- "Rostock"
	v[v %in% sipoo] <- "Sipoo"
	v[v %in% sortavala] <- "Sortavala"
	v[v %in% strangnas] <- "Strängnäs"
	v[v %in% tallinna] <- "Tallinna"
	v[v %in% tammisaari] <- "Tammisaari"
	v[v %in% tampere] <- "Tampere"
	v[v %in% tartto] <- "Tartto"
	v[v %in% tukholma] <- "Tukholma"
	v[v %in% turenki] <- "Turenki"
	v[v %in% turku] <- "Turku"
	v[v %in% uppsala] <- "Uppsala"
	v[v %in% uusikaarlepyy] <- "Uusikaarlepyy"
	v[v %in% uusikaupunki] <- "Uusikaupunki"
	v[v %in% vaasa] <- "Vaasa"
	v[v %in% viipuri] <- "Viipuri"
	v[v %in% wittenberg] <- "Wittenberg"

	v
}

df$pub_where <- correct_misspellings(df$pub_where)
