---
title: "Drop in the beginning of 19th century"
date: "14 heinäkuuta 2016"
output: pdf_document
---

```{r 201607krakow-fennica_drop, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, cache=TRUE}
# Default time span
min.year <- 1484
max.year <- 1828

library(ggmap)
library(gisfin)
library(stringr)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)

library(fennica)
library(sorvi)
library(devtools)
# install_github("ropengov/gisfin")
# devtools::install_github('cttobin/ggthemr')
#library(ggthemr)

knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(fig.path = "slides_201606_Krakow/", dev="CairoPNG")
knitr::opts_chunk$set(fig.path = "slides_201606_Krakow/")

# Set locale
tmp <- Sys.setlocale(locale="UTF-8") 

# Nice theme
theme_set(theme_bw(26))
```

```{r 201607krakow-fennica_drop2, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, cache=TRUE}
# Full combined catalogue (Fen + Kun) with marked duplicates

df.combined.preprocessed <- readRDS("df.combined.Rds")

# Data with duplicates removed
df.full <- df.combined.preprocessed %>% filter(!remove)


# What did each of the Kongliga tryckare publish?
df0 <- df.full %>% filter(publication_year >= 1700 & publication_year <= 1827 & publication_place == "Turku")

df0$publ <- NA
df0$publ[intersect(grep("Merckell",df0$publisher), grep("Henric", df0$publisher))] <- "Gezelius/Merckell"
df0$publ[grep("Winter",df0$publisher)] <- "Gezelius/Merckell"
df0$publ[grep("(Hjelt|Piplia|Biblia|Bibel)", df0$publisher)] <- "Hjelt"
df0$publ[which(is.na(df0$publ))] <- "Frenckell"

df0 <- df0 %>% filter(publ=="Frenckell")
df0$publ <- NA
df0$publ[df0$publication_year <= 1710] <- "Johan Wall"
df0$publ[intersect(which(df0$publication_year == 1711), grep("Wall", df0$publisher))] <- "Johan Wallin leski"
df0$publ[intersect(which(df0$publication_year <= 1713), intersect(which(df0$publication_year >= 1710), grep("Björckman", df0$publisher)))] <-"Anders Björckman"
df0$publ[intersect(which(df0$publication_year <= 1729), intersect(which(df0$publication_year >= 1722), grep("Flodström", df0$publisher)))] <-"Eric Flodström"
df0$publ[intersect(which(df0$publication_year <= 1753), intersect(which(df0$publication_year >= 1729), grep("Kämpe", df0$publisher)))] <-"Johan Kämpe"
df0$publ[intersect(which(df0$publication_year <= 1761), intersect(which(df0$publication_year >= 1750), grep("Merckell", df0$publisher)))] <-"Eric Flodström"
df0$publ[intersect(which(df0$publication_year <= 1779), intersect(which(df0$publication_year >= 1761), grep("leski", df0$publisher, invert = TRUE)))] <-"Frenckell I"
df0$publ[intersect(which(df0$publication_year <= 1785), intersect(which(df0$publication_year >= 1779), grep("Frenckell", df0$publisher)))] <-"Frenckell I:n leski"
df0$publ[intersect(which(df0$publication_year <= 1814), intersect(which(df0$publication_year >= 1785), grep("Frenckell", df0$publisher)))] <-"Frenckell II"
df0$publ[intersect(which(df0$publication_year <= 1856), intersect(which(df0$publication_year >= 1814), grep("Frenckell", df0$publisher)))] <-"Frenckell II & poika"
df0$publ[intersect(which(df0$publication_year <= 1876), intersect(which(df0$publication_year >= 1856), grep("Frenckell", df0$publisher)))] <-"Frenckellin kirjapaino"

unique_publisher = unique(df0$publisher)
message("greppausten jälkeen")
# What did Henric Merckell publish?
df0 <- df.full %>% filter(publication_year >= min.year & publication_year <= max.year & publisher=="Merckell, Henric Christopher")


df <- df0 %>% filter(publication_year >=1700 & publication_year <=1828) %>% group_by(publication_decade, leaflet=(pagecount <= 10), dissertation, publication_place) %>% tally()

df$leaflet[df$leaflet==TRUE] <- " <= 10 pages"
df$leaflet[df$leaflet==FALSE] <- " > 10 pages"

l <- (df %>% group_by(leaflet) %>% group_by(dissertation))
df$l <- paste0(l$dissertation, l$leaflet)
message("random kohta")
unique_diss <- unique(na.omit(df$dissertation))
unique_leaflet <- unique(na.omit(df$leaflet))
publisher = "Henric Christopher Merckell"
#df <- df %>% filter(n > 10)
message("before loop")
  for (diss in unique_diss) {
    for (leaflet in unique_leaflet) {
      message("In loop")
      #if (length(which(df$dissertation==diss)) > 10) {
      
      
        p <- ggplot(df[which(df$dissertation==diss & df$leaflet==leaflet),], aes(x = publication_decade, y = n, fill=publication_place)) + 
        geom_bar(position = "dodge", stat = "identity") + 
        xlab("Publication year") +
        ylab("Documents (n)") +
        scale_fill_discrete(name = "Publication place") + 
          ggtitle(paste0(publisher, "\nDissertations = ", diss, "\nBook length ", leaflet))
        print(p)
        print(paste0("Dissertations = ", diss))
        print(paste0("Book length ", leaflet))
      #}
    }
  }












# Data with years limited as well
df0 <- df.full %>% filter(publication_year >= min.year & publication_year <= max.year & publication_place=="Turku")
# Fennica only
df0 <- df0 %>% filter(catalog=="Fennica")
catalog="Fennica"

df <- df0 %>% filter(publication_year >=1700 & publication_year <=1828) %>% group_by(publication_decade, leaflet=(pagecount <= 10), dissertation, publisher, publ=NA) %>% tally()

#df <- df0 %>% filter(publication_year >=1700 & publication_year <=1828) %>% group_by(publication_decade, leaflet=(pagecount <= 10), dissertation, publisher) %>% tally()

df$leaflet[df$leaflet==TRUE] <- " <= 10 pages"
df$leaflet[df$leaflet==FALSE] <- " > 10 pages"
unique_publisher <- unique(df$publisher)

l <- (df %>% group_by(leaflet) %>% group_by(publisher))
df$l <- paste0(l$publisher, l$leaflet)

df$publ[intersect(grep("Merckell",df$publisher), grep("Henric", df$publisher))] <- "Gezelius/Merckell"
df$publ[grep("Winter",df$publisher)] <- "Gezelius/Merckell"
df$publ[grep("(Hjelt|Piplia)", df$publisher)] <- "Hjelt"
df$publ[which(is.na(df$publ))] <- "Frenckell"

unique_publ <- unique(df$publ)
unique_diss <- unique(na.omit(df$dissertation))
unique_leaflet <- unique(na.omit(df$leaflet))
df <- df %>% filter(n > 10)
for (publ in unique_publ) {
  for (diss in unique_diss) {
    for (leaflet in unique_leaflet) {
      if (length(which(df$dissertation==diss & df$publ==publ)) > 10) {
      
      
        p <- ggplot(df[which(df$dissertation==diss & df$publ==publ & df$leaflet==leaflet),], aes(x = publication_decade, y = n, fill=publisher)) + 
        geom_bar(position = "dodge", stat = "identity") + 
        xlab("Publication year") +
        ylab("Documents (n)") +
        scale_fill_discrete(name = "New Legend Title")
        ggtitle("DROP")
    
        print(p)
        print(paste0("Dissertations = ", diss))
        print(paste0("Publishing house = ", publ))
        print(paste0("Book length ", leaflet))
    
    }
  }
}
}






#print(df)
unique_publ <- unique(df$publ)
unique_diss <- unique(na.omit(df$dissertation))
for (publ in unique_publ) {
  for (diss in unique_diss) {
    if (length(which(df$dissertation==diss & df$publ==publ)) > 0) {
      
    
      p <- ggplot(df[which(df$dissertation==diss & df$publ==publ),], aes(x = publication_decade, y = n, fill=leaflet)) + 
      geom_bar(position = "dodge", stat = "identity") + 
      xlab("Publication year") +
      ylab("Documents (n)") +
      #guides(fill = guide_legend(reverse = TRUE, title = "")) +
      #scale_fill_manual(values=c("blue", "red")) + 
      scale_fill_discrete(name = "New Legend Title")
      ggtitle("DROP")
    
  #p <- ggplot(df[which(df$dissertation==diss),], aes(x = publication_decade, y = n, color = leaflet)) + 
  #       geom_point() + 
  #     geom_line()
  #       ylab("Documents (n)") + xlab("Publication year") +
  #       scale_color_manual(values = c("blue", "darkgreen")) + 
  #       guides(color = guide_legend(reverse = TRUE, title = "")) #+ 
  
      print(p)
      print(paste0("Dissertations = ", diss))
      print(paste0("Publishing house = ", publ))
    
    }
  }
}
```
