---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    logo: ropengov.png
    favicon: HY-CC.png
    theme: default
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "About", href: "https://example.com/about", align: left }
    social: [ "menu" ]
    source_code: http://github.com/antagomir
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r init, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE, cache=FALSE}
library(ggmap)
library(gisfin)
library(stringr)
library(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)

library(fennica)
library(sorvi)
library(devtools)
# install_github("ropengov/gisfin")
# devtools::install_github('cttobin/ggthemr')
#library(ggthemr)
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(fig.path = "figure_slides/", dev="CairoPNG")
knitr::opts_chunk$set(fig.path = "figure_flex/")

# Set locale
tmp <- Sys.setlocale(locale="UTF-8") 

# Nice theme
theme_set(theme_bw(26))

# Params
min.year <- 1470
max.year <- 1828

# Full combined catalogue (Fen + Kun) with marked duplicates
df.combined.preprocessed <- readRDS("df.combined.Rds")
# Data with duplicates removed and years limited
df0 <- df.combined.preprocessed %>% filter(!remove) %>%
	   			    filter(publication_year >= min.year &
					   publication_year <= max.year)
```



Page 1
==============================================================================


Column {data-width=650}
-----------------------------------------------------------------------

Flexdashboard instructions:
  * [Usage](http://rmarkdown.rstudio.com/flexdashboard/using.html)
  * [htmlwidget gallery](http://gallery.htmlwidgets.org/)
  * [flexdashboard examples](http://rmarkdown.rstudio.com/flexdashboard/examples.html)
  * [plotly](https://plot.ly/r/)

### Linked Value Box

```{r}
valueBox(42, icon = "fa-pencil", href="#page-2")
```

### Table

```{r}
library(shiny)
#renderTable({head(mtcars)})
#renderTable({head(mtcars, n = input$rows)})

library(DT)
DT::datatable(mtcars, options = list(bPaginate = FALSE))
#DT::datatable(mtcars, options = list(pageLength = 25))
```

<!--Column {data-width=350}-->
Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B


```{r map1, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggmap)
library(ggplot2)
library(gisfin)
source("funcs.R")
theme_set(get_theme_map())
i <- 1650
mapdata1 <- filter(df0,
              publication_decade == i &
              (catalog == "Kungliga" & 
	            publication_place %in% c("Stockholm", "Uppsala",
	                         "Greifswald", "Lund", "Tartu"))|
	  (catalog == "Fennica" &
	      publication_place == "Turku")) %>%
      group_by(publication_decade, publication_place,
	       latitude, longitude) %>%
      summarise(n = n()) 

mapdata <- bind_rows(mapdata1, 
  as.data.frame(list(publication_decade = 1650, publication_place = "Lund", 
                     latitude = 55.70293, longitude = 13.19294, n = 0)))

mapdata$size <- mapdata$n
mapdata$highlight <- rep("black", nrow(mapdata))
mapdata$highlight[mapdata$publication_place %in% c("Turku")] <- "red"
mapdata$highlight <- factor(mapdata$highlight)

mapdata$highlight2 <- rep(1, nrow(mapdata))
mapdata$highlight2[mapdata$publication_place %in% c("Greifswald", "Lund")] <- 9
mapdata$highlight2 <- factor(mapdata$highlight2)

region <- c(8, 40, 31, 76)
names(region) <- c("left", "bottom", "right", "top")
#mymap <- get_map(location=geobox(region), color = "bw", source="osm",  maptype="terrain")
#mymap <- get_map(location=geobox(region), source="stamen", maptype = "watercolor")
mymap <- get_map(location=geobox(region), maptype="roadmap")

# Pick the investigated period (sliding window)
# Sum up the years within this sliding window for each element    	    
dfw <- mapdata %>%
    	     group_by(publication_place, latitude, longitude, highlight, highlight2) %>%
		       summarize(n = sum(size))
dfw$size <- log10(1 + dfw$n)
dfw$size[!dfw$highlight2 == 1] <- 0.5*max(dfw$size)
    

# Plot map
p <- ggmap(mymap) + 

        	geom_point(data = subset(dfw, highlight2 == 1),
      	    aes(
      	      x = longitude, 
      	      y = latitude,
	            size = size,
	            shape = 1, 
	            #shape = highlight2, 
	            fill = highlight), 
      	      pch = 21, stroke = 1) +
  
        	geom_point(data = subset(dfw, !highlight2 == 1),
      	    aes(
      	      thickness = 10,
      	      x = longitude, 
      	      y = latitude,
	            shape = 19, 
	            #shape = highlight2, 
	            color = highlight), 
      	      colour = "black", 
      	      shape = 21, # Point shape 
      	      size = 7,   # Point size
      	      stroke = 1.5) + # Point edge thickness
  
  
	        ggtitle(i) +
	        scale_size(range = c(2, 15)) +
	        theme(title = element_text(size = 30), legend.position="none") +
	        scale_fill_manual(values = c("darkgray", "red")) #+
	        #scale_shape_manual(values = c(19,1))
print(p)
```

Map by Stamen


### Chart C


```{r}
library(dygraphs)
dygraph(ldeaths)
```

Page 2
=====================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```


