knit("summary.Rmd", encoding="UTF-8")
knit("Helsinki.Rmd", encoding="UTF-8")
knit("Suomi.Rmd", encoding="UTF-8")
knit("Turku.Rmd", encoding="UTF-8")
knit("Vaasa.Rmd", encoding="UTF-8")
knit("suvut.Rmd", encoding="UTF-8")
