---
title: "Digital History in Finland, 1488-1828"
author: "Mikko Tolonen, Jani Marjanen, Hege Roivainen, Leo Lahti"
date: "June 22, 2016"
output: markdown_document
---

```{r 201606krakow-init, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)
library(bibliographica)
library(fennica)
library(sorvi)

# Nice theme
theme_set(theme_bw(26))

# Figure path
opts_chunk$set(fig.path = "figure_201606_Krakow/")

# Define time span
min.year = 1470
max.year = 1828

# Read data
fen <- readRDS("df.Rds")
kun <- readRDS("../../../kungliga/antagomir/df.Rds")

fen <- fen %>% filter(publication_year >= min.year & publication_year <= max.year)
kun <- kun %>% filter(publication_year >= min.year & publication_year <= max.year)
```


```{r 201606krakow-turkuvsother, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
df <- fen %>% 
      filter(!is.na(country)) %>%
      filter(!is.na(publication_place) & !is.na(paper.consumption.km2) & paper.consumption.km2 > -0.01)

# Add indicator field: Turku or Not Turku
myplace <- "Turku"

df$myplace <- rep(NA, nrow(df))
df$myplace[df$publication_place == myplace] <- myplace
df$myplace[!df$publication_place == myplace & df$country == "Finland"] <- "Finland"
df$myplace[!df$country == "Finland" & !df$publication_place == myplace] <- "Foreign"
df$myplace <- factor(df$myplace, levels = rev(c("Foreign", "Finland", "Turku")))

# Keep entries with known publication place and paper consumption
# Group by year/decade and Turku/Other
dfs <- df %>% group_by(publication_decade, myplace) %>%
  summarise(titles = n(), paper = sum(paper.consumption.km2, na.rm = TRUE))

p <- ggplot(dfs, aes(x = publication_decade, y = paper, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Paper consumption") +
     #scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE, title = "")) + 
     xlab("Publication decade") + ylab("Paper (km2)")
print(p)


p <- ggplot(dfs, aes(x = publication_decade, y = titles, fill = myplace, order = -as.numeric(myplace))) +
     geom_bar(position = "stack", stat = "identity", color = "black") +
     ggtitle("Title count") +
     # scale_fill_manual(values = c("blue", "black", "darkgreen")) +
     scale_fill_grey() +
     guides(fill = guide_legend(reverse = TRUE, title = "")) +      
     xlab("Publication decade") + ylab("Title count (n)")
print(p)
```

