# Fennica preprocessing summary

The original data set contains `r nrow(df.orig)` documents.

The following fields have been harmonized.

  * [Author date](author_date.html)
  * [Author name](author_name.html)
  * [Gender info](gender.html)
  * [Publisher info](publisher.html)
  * [Publication geography](publication_place.html)
  * [Publication year info](publication_time.html)
  * [Publication year info](publication_frequency.html)
  * [Publication year info](publication_interval.html)
  * [Titles](title.html)  
  * [Page counts](pagecount.html)
  * [Physical dimension](dimension.html)    
  * [Document and subject topics](topic.html)
  * [Languages](language.html)
  * [Corporate](corporate.html)
  * [Holder](holder.html)
  * [Note_510c](note_510c.html)
  * [Note_dissertation](note_dissertation.html)
  * [Note_granter](note_granter.html)
  * [Note_source](note_source.html)
  * [Subject_topic](subject_topic.html)
  * [Successor](successor.html)
  * [Title_uniform](title_uniform.html)
  * [Uncontrolled](uncontrolled.html)
See also [further preprocessing details](details.Rhtml).

