---
title: "Paper Consumption in Finland, 1488-1828"
author: "Niko Ilomäki"
date: "December 7, 2015"
output: markdown_document
---

```{r summaryinit, echo=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)

library(fennica)
library(sorvi)
df <- readRDS("df.Rds")
dfs <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
authors <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  group_by(author_name) %>%
  summarise(titles=n()) %>% arrange(desc(titles))
top10.authors <- tail(head(authors,11),10)
df.authors <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(author_name %in% c(top10.authors$author_name)) %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
df.Turku <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(publication_place == "Turku") %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
df.Tukholma <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(publication_place == "Stockholm") %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
df.Vaasa <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(publication_place == "Vaasa") %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
df.Uppsala <- df %>% filter(publication_year > 1400 & publication_year < 1829) %>%
  filter(publication_place == "Uppsala") %>%
  filter(!is.na(paper) & paper > -0.01) %>%
  group_by(publication_year) %>%
  summarise(titles = n(), paper = sum(paper))
```

```{r titles, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1 <- ggplot(dfs, aes(y = titles, x = publication_year))
p1 <- p1 + geom_smooth(color = "black") + geom_point()
p1 <- p1 + xlab("Publication Year") + ylab("Title Count") 
p1 <- p1 + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1 <- p1 + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1 <- p1 + guides(fill = "none", alpha = "none")
p1 <- p1 + ggtitle("Finnish publications 1488-1828: title count (all authors)")
print(p1)
```

```{r paper, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2 <- ggplot(dfs, aes(y = paper, x = publication_year))
p2 <- p2 + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2 <- p2 + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2 <- p2 + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2 <- p2 + guides(fill = "none", alpha = "none")
p2 <- p2 + ggtitle("Finnish publications 1488-1828: paper consumption (all authors)")
print(p2)
```

```{r titles10, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1b <- ggplot(df.authors, aes(y = titles, x = publication_year))
p1b <- p1b + geom_smooth(color = "black") + geom_point()
p1b <- p1b + xlab("Publication Year") + ylab("Title Count") 
p1b <- p1b + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1b <- p1b + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1b <- p1b + guides(fill = "none", alpha = "none")
p1b <- p1b + ggtitle("Finnish publications 1488-1828: title count (top 10 authors)")
print(p1b)
```

```{r paper10, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2b <- ggplot(df.authors, aes(y = paper, x = publication_year))
p2b <- p2b + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2b <- p2b + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2b <- p2b + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2b <- p2b + guides(fill = "none", alpha = "none")
p2b <- p2b + ggtitle("Finnish publications 1488-1828: paper consumption (top 10 authors)")
print(p2b)
```

```{r titlesTurku, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1.Turku <- ggplot(df.Turku, aes(y = titles, x = publication_year))
p1.Turku <- p1.Turku + geom_smooth(color = "black") + geom_point()
p1.Turku <- p1.Turku + xlab("Publication Year") + ylab("Title Count") 
p1.Turku <- p1.Turku + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1.Turku <- p1.Turku + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1.Turku <- p1.Turku + guides(fill = "none", alpha = "none")
p1.Turku <- p1.Turku + ggtitle("Finnish publications in Turku, 1488-1828: title count")
print(p1.Turku)
```

```{r paperTurku, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2.Turku <- ggplot(df.Turku, aes(y = paper, x = publication_year))
p2.Turku <- p2.Turku + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2.Turku <- p2.Turku + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2.Turku <- p2.Turku + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2.Turku <- p2.Turku + guides(fill = "none", alpha = "none")
p2.Turku <- p2.Turku + ggtitle("Finnish publications in Turku, 1488-1828: paper consumption")
print(p2.Turku)
```

```{r titlesTukholma, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1.Tukholma <- ggplot(df.Tukholma, aes(y = titles, x = publication_year))
p1.Tukholma <- p1.Tukholma + geom_smooth(color = "black") + geom_point()
p1.Tukholma <- p1.Tukholma + xlab("Publication Year") + ylab("Title Count") 
p1.Tukholma <- p1.Tukholma + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1.Tukholma <- p1.Tukholma + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1.Tukholma <- p1.Tukholma + guides(fill = "none", alpha = "none")
p1.Tukholma <- p1.Tukholma + ggtitle("Finnish publications in Stockholm, 1488-1828: title count")
print(p1.Tukholma)
```

```{r paperTukholma, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2.Tukholma <- ggplot(df.Tukholma, aes(y = paper, x = publication_year))
p2.Tukholma <- p2.Tukholma + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2.Tukholma <- p2.Tukholma + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2.Tukholma <- p2.Tukholma + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2.Tukholma <- p2.Tukholma + guides(fill = "none", alpha = "none")
p2.Tukholma <- p2.Tukholma + ggtitle("Finnish publications in Stockholm, 1488-1828: paper consumption")
print(p2.Tukholma)
```

```{r titlesVaasa, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1.Vaasa <- ggplot(df.Vaasa, aes(y = titles, x = publication_year))
p1.Vaasa <- p1.Vaasa + geom_smooth(color = "black") + geom_point()
p1.Vaasa <- p1.Vaasa + xlab("Publication Year") + ylab("Title Count") 
p1.Vaasa <- p1.Vaasa + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1.Vaasa <- p1.Vaasa + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1.Vaasa <- p1.Vaasa + guides(fill = "none", alpha = "none")
p1.Vaasa <- p1.Vaasa + ggtitle("Finnish publications in Vaasa, 1488-1828: title count")
print(p1.Vaasa)
```

```{r paperVaasa, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2.Vaasa <- ggplot(df.Vaasa, aes(y = paper, x = publication_year))
p2.Vaasa <- p2.Vaasa + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2.Vaasa <- p2.Vaasa + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2.Vaasa <- p2.Vaasa + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2.Vaasa <- p2.Vaasa + guides(fill = "none", alpha = "none")
p2.Vaasa <- p2.Vaasa + ggtitle("Finnish publications in Vaasa, 1488-1828: paper consumption")
print(p2.Vaasa)
```

```{r titlesUppsala, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8}
p1.Uppsala <- ggplot(df.Uppsala, aes(y = titles, x = publication_year))
p1.Uppsala <- p1.Uppsala + geom_smooth(color = "black") + geom_point()
p1.Uppsala <- p1.Uppsala + xlab("Publication Year") + ylab("Title Count") 
p1.Uppsala <- p1.Uppsala + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p1.Uppsala <- p1.Uppsala + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p1.Uppsala <- p1.Uppsala + guides(fill = "none", alpha = "none")
p1.Uppsala <- p1.Uppsala + ggtitle("Finnish publications in Uppsala, 1488-1828: title count")
print(p1.Uppsala)
```

```{r paperUppsala, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, fig.height=4, fig.width=8.2}
p2.Uppsala <- ggplot(df.Uppsala, aes(y = paper, x = publication_year))
p2.Uppsala <- p2.Uppsala + geom_smooth(color = "black") + geom_point() +
       xlab("Publication Year") +
       ylab("Paper Consumption")
       
p2.Uppsala <- p2.Uppsala + theme(axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20))
p2.Uppsala <- p2.Uppsala + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p2.Uppsala <- p2.Uppsala + guides(fill = "none", alpha = "none")
p2.Uppsala <- p2.Uppsala + ggtitle("Finnish publications in Uppsala, 1488-1828: paper consumption")
print(p2.Uppsala)
```
