---
title: "Julkaisutoiminta Turussa 1640-1917"
author: "Niko Ilomäki"
date: "`r Sys.Date()`"
output: markdown_document
---

```{r, echo=FALSE, message=FALSE}
library(dplyr)
```

```{r, echo=FALSE, message=FALSE}
# data ei välttämättä lopullinen
df <- readRDS("df.Rds")
df <- df %>% filter(!is.na(published_in))
tmp1 <- df %>% filter(publication_place == "Turku") %>% group_by(published_in) %>% tally() %>% arrange(published_in)
tmp1$decade <- as.numeric(paste0(substr(tmp1$published_in,1,3),"0"))
tmp2 <- tmp1 %>% group_by(decade) %>% summarise(m = sum(n)/10)
final <- inner_join(tmp1,tmp2)
```

```{r Turku, echo=FALSE, fig.width=20, fig.height=10}
par(las=1)
par(mgp=c(10,3,0))
par(mar=c(7,17,6,4))
plot(final$published_in,final$n,cex=1.8,pch="|",cex.main=5.0,main="Julkaisutoiminta Turussa 1640-1917",cex.lab=5.0,xlab="",ylab="Dokumenttia / vuosi",axes=FALSE,col="black")
lines(final$published_in,final$m,type="l",lty=3,col="black",lwd=4)
axis(side = 1, at = c(1640,1809,1863,1917),cex.axis=3.2)
axis(side = 2, at = c(0,35,70,105,140,169),cex.axis=3.2)
```

```{r, echo=FALSE}
remove(tmp1,tmp2,final)
```
