counts_total(df.full)

counts_by_town(df.full,"Helsinki", "Helsinki")
counts_by_town(df.full,"Turku", "Turku")
counts_by_town(df.full,"Porvoo", "Porvoo")
counts_by_town(df.full,"Tukholma", "Tukholma")
counts_by_town(df.full,"Vaasa", "Vaasa")
counts_by_town(df.full,"Tampere", "Tampere")
counts_by_town(df.full,"Kuopio","Kuopio")
counts_by_town(df.full,"Hämeenlinna","Hameenlinna")
counts_by_town(df.full,"Viipuri","Viipuri")
counts_by_town(df.full,"Jyväskylä","Jyvaskyla")

counts_by_language(df.full,"language_fin","lang_finnish")
counts_by_language(df.full,"language_swe","lang_swedish")
counts_by_language(df.full,"language_lat","lang_latin")
counts_by_language(df.full,"language_ger","lang_german")
counts_by_language(df.full,"language_eng","lang_english")
counts_by_language(df.full,"language_fre","lang_french")
counts_by_language(df.full,"language_rus","lang_russian")
counts_by_language(df.full,"language_gre","lang_greek")
counts_by_language(df.full,"language_dan","lang_danish")
