correct_misspellings <- function(v) {
	v[v %in% city$almena] <- "Almena WI"
	v[v %in% city$altdorf] <- "Altdorf"
	v[v %in% city$ashtabula] <- "Ashtabula OH"
	v[v %in% city$astoria] <- "Astoria OR"
	v[v %in% city$berliini] <- "Berliini"
	v[v %in% city$boston] <- "Boston MA"
	v[v %in% city$bridgeport] <- "Bridgeport CT"
	v[v %in% city$bronx] <- "Bronx NY"
	v[v %in% city$brooklyn] <- "Brooklyn NY"
	v[v %in% city$calumet] <- "Calumet MI"
	v[v %in% city$chicago] <- "Chicago IL"
	v[v %in% city$chisholm] <- "Chisholm MN"
	v[v %in% city$cincinnati] <- "Cincinnati OH"
	v[v %in% city$cleveland] <- "Cleveland OH"
	v[v %in% city$duluth] <- "Duluth MN"
	v[v %in% city$espoo] <- "Espoo"
	v[v %in% city$fitchburg] <- "Fitchburg MA"
	v[v %in% city$giessen] <- "Giessen"
	v[v %in% city$goteborg] <- "Göteborg"
	v[v %in% city$gottingen] <- "Göttingen"
	v[v %in% city$greifswald] <- "Greifswald"
	v[v %in% city$haaparanta] <- "Haaparanta"
	v[v %in% city$hamina] <- "Hamina"
	v[v %in% city$hampuri] <- "Hampuri"
	v[v %in% city$hancock] <- "Hancock MI"
	v[v %in% city$hanko] <- "Hanko"
	v[v %in% city$helsinki] <- "Helsinki"
	v[v %in% city$hameenlinna] <- "Hämeenlinna"
	v[v %in% city$ironwood] <- "Ironwood MI"
	v[v %in% city$ishpeming] <- "Ishpeming MI"
	v[v %in% city$jena] <- "Jena"
	v[v %in% city$jyvaskyla] <- "Jyväskylä"
	v[v %in% city$kaleva] <- "Kaleva MI"
	v[v %in% city$kaliningrad] <- "Kaliningrad"
	v[v %in% city$karjaa] <- "Karjaa"
	v[v %in% city$kaskinen] <- "Kaskinen"
	v[v %in% city$kiel] <- "Kiel"
	v[v %in% city$kokkola] <- "Kokkola"
	v[v %in% city$kotka] <- "Kotka"
	v[v %in% city$kouvola] <- "Kouvola"
	v[v %in% city$kristiinankaupunki] <- "Kristiinankaupunki"
	v[v %in% city$kruunupyy] <- "Kruunupyy"
	v[v %in% city$kuopio] <- "Kuopio"
	v[v %in% city$koln] <- "Köln"
	v[v %in% city$koopenhamina] <- "Kööpenhamina"
	v[v %in% city$lahti] <- "Lahti"
	v[v %in% city$lappeenranta] <- "Lappeenranta"
	v[v %in% city$leiden] <- "Leiden"
	v[v %in% city$linkoping] <- "Linköping"
	v[v %in% city$lontoo] <- "Lontoo"
	v[v %in% city$loviisa] <- "Loviisa"
	v[v %in% city$lund] <- "Lund"
	v[v %in% city$lyypekki] <- "Lyypekki"
	v[v %in% city$maarianhamina] <- "Maarianhamina"
	v[v %in% city$magdeburg] <- "Magdeburg"
	v[v %in% city$marburg] <- "Marburg"
	v[v %in% city$mikkeli] <- "Mikkeli"
	v[v %in% city$milwaukee] <- "Milwaukee WI"
	v[v %in% city$minneapolis] <- "Minneapolis MN"
	v[v %in% city$moskova] <- "Moskova"
	v[v %in% city$nanaimo] <- "Nanaimo BC"
	v[v %in% city$narva] <- "Narva"
	v[v %in% city$newyork] <- "New York NY"
	v[v %in% city$newyorkmills] <- "New York Mills MN"
	v[v %in% city$oslo] <- "Oslo"
	v[v %in% city$oulu] <- "Oulu"
	v[v %in% city$pariisi] <- "Pariisi"
	v[v %in% city$philadelphia] <- "Philadelphia PA"
	v[v %in% city$pietari] <- "Pietari"
	v[v %in% city$pietarsaari] <- "Pietarsaari"
	v[v %in% city$pori] <- "Pori"
	v[v %in% city$portarthur] <- "Port Arthur ON"
	v[v %in% city$portland] <- "Portland OR"
	v[v %in% city$porvoo] <- "Porvoo"
	v[v %in% city$parnu] <- "Pärnu"
	v[v %in% city$quincy] <- "Quincy MA"
	v[v %in% city$rauma] <- "Rauma"
	v[v %in% city$riika] <- "Riika"
	v[v %in% city$rockisland] <- "Rock Island IL"
	v[v %in% city$rooma] <- "Rooma"
	v[v %in% city$rostock] <- "Rostock"
	v[v %in% city$seattle] <- "Seattle WA"
	v[v %in% city$sipoo] <- "Sipoo"
	v[v %in% city$smithville] <- "Smithville MN"
	v[v %in% city$sortavala] <- "Sortavala"
	v[v %in% city$strangnas] <- "Strängnäs"
	v[v %in% city$superior] <- "Superior WI"
	v[v %in% city$tallinna] <- "Tallinna"
	v[v %in% city$tammisaari] <- "Tammisaari"
	v[v %in% city$tampere] <- "Tampere"
	v[v %in% city$tartto] <- "Tartto"
	v[v %in% city$tukholma] <- "Tukholma"
	v[v %in% city$turenki] <- "Turenki"
	v[v %in% city$turku] <- "Turku"
	v[v %in% city$uppsala] <- "Uppsala"
	v[v %in% city$uusikaarlepyy] <- "Uusikaarlepyy"
	v[v %in% city$uusikaupunki] <- "Uusikaupunki"
	v[v %in% city$vaasa] <- "Vaasa"
	v[v %in% city$viipuri] <- "Viipuri"
	v[v %in% city$vasteros] <- "Västerås"
	v[v %in% city$wittenberg] <- "Wittenberg"
	v[v %in% city$worcester] <- "Worcester MA"

	# several cities
	v[v=="Stockholmisa ja Turusa"] <- "Tukholma; Turku"
	v[v=="Stockholm och Åbo"] <- "Tukholma; Turku"
	v[v=="Stockholm; Helsingfors"] <- "Tukholma; Helsinki"
	v[v=="Stockholm Upsala och Åbo"] <- "Tukholma; Uppsala; Turku"

	# misc
	v[v=="Kristiina"] <- "Kristiinankaupunki" # vai Ristiina
	v[v=="Pest"] <- "Budapest" # ???
	v[v=="Hernösand"] <- "Härnösand"
	v[v=="Carlscrona"] <- "Karlskrona"

	v
}
