#' @title deduce_country
#' @description Add country field to data frame based on city field
#'
#' @param city City vector
#' @return Country vector
#'
#' @export
#' 
#' @author Niko Ilomaki \email{niko.ilomaki@@helsinki.fi}
#' @references See citation("fennica")
#' 
#' @examples \dontrun{country <- deduce_country(c("Helsinki","Tukholma"))}
#' @keywords utilities
deduce_country <- function(city) {
	country <- rep(NA, length(city))
	country[city=="Almena WI"] <- "USA"
	country[city=="Altdorf"] <- "Saksa"
	country[city=="Amsterdam"] <- "Alankomaat"
	country[city=="Ashtabula OH"] <- "USA"
	country[city=="Astoria OR"] <- "USA"
	country[city=="Barcelona"] <- "Espanja"
	country[city=="Berliini"] <- "Saksa"
	country[city=="Boston MA"] <- "USA"
	country[city=="Braunschweig"] <- "Saksa"
	country[city=="Bridgeport CT"] <- "USA"
	country[city=="Bronx NY"] <- "USA"
	country[city=="Brooklyn NY"] <- "USA"
	country[city=="Calumet MI"] <- "USA"
	country[city=="Chicago IL"] <- "USA"
	country[city=="Chisholm MN"] <- "USA"
	country[city=="Cincinnati OH"] <- "USA"
	country[city=="Cleveland OH"] <- "USA"
	country[city=="Budapest"] <- "Unkari"
	country[city=="Dresden"] <- "Saksa"
	country[city=="Duluth MN"] <- "USA"
	country[city=="Espoo"] <- "Suomi"
	country[city=="Eura"] <- "Suomi"
	country[city=="Firenze"] <- "Italia"
	country[city=="Fitchburg MA"] <- "USA"
	country[city=="Forssa"] <- "Suomi"
	country[city=="Frankfurt"] <- "Saksa"
	country[city=="Giessen"] <- "Saksa"
	country[city=="Göteborg"] <- "Ruotsi"
	country[city=="Göttingen"] <- "Saksa"
	country[city=="Greifswald"] <- "Saksa"
	country[city=="Haaparanta"] <- "Suomi"
	country[city=="Hamina"] <- "Suomi"
	country[city=="Hampuri"] <- "Saksa"
	country[city=="Hancock MI"] <- "USA"
	country[city=="Hanko"] <- "Suomi"
	country[city=="Heinola"] <- "Suomi"
	country[city=="Helsinki"] <- "Suomi"
	country[city=="Hyvinkää"] <- "Suomi"
	country[city=="Hämeenlinna"] <- "Suomi"
	country[city=="Iisalmi"] <- "Suomi"
	country[city=="Ironwood MI"] <- "USA"
	country[city=="Ishpeming MI"] <- "USA"
	country[city=="Jena"] <- "Saksa"
	country[city=="Joensuu"] <- "Suomi"
	country[city=="Jyväskylä"] <- "Suomi"
	country[city=="Kajaani"] <- "Suomi"
	country[city=="Kaleva MI"] <- "USA"
	country[city=="Kaliningrad"] <- "Venäjä" #huom!
	country[city=="Karjaa"] <- "Suomi"
	country[city=="Kaskinen"] <- "Suomi"
	country[city=="Kemi"] <- "Suomi"
	country[city=="Kiel"] <- "Saksa"
	country[city=="Kokkola"] <- "Suomi"
	country[city=="Kotka"] <- "Suomi"
	country[city=="Kouvola"] <- "Suomi"
	country[city=="Kristiinankaupunki"] <- "Suomi"
	country[city=="Kruunupyy"] <- "Suomi"
	country[city=="Kuopio"] <- "Suomi"
	country[city=="Käkisalmi"] <- "Suomi"
	country[city=="Köln"] <- "Saksa"
	country[city=="Kööpenhamina"] <- "Tanska"
	country[city=="Laihia"] <- "Suomi"
	country[city=="Lahti"] <- "Suomi"
	country[city=="Lappeenranta"] <- "Suomi"
	country[city=="Lapua"] <- "Suomi"
	country[city=="Leiden"] <- "Saksa"
	country[city=="Leipzig"] <- "Saksa"
	country[city=="Linköping"] <- "Ruotsi"
	country[city=="Lontoo"] <- "UK"
	country[city=="Loviisa"] <- "Suomi"
	country[city=="Lund"] <- "Ruotsi"
	country[city=="Lyypekki"] <- "Saksa"
	country[city=="Maarianhamina"] <- "Suomi"
	country[city=="Magdeburg"] <- "Saksa"
	country[city=="Marburg"] <- "Saksa"
	country[city=="Mikkeli"] <- "Suomi"
	country[city=="Milwaukee WI"] <- "USA"
	country[city=="Minneapolis MN"] <- "USA"
	country[city=="Moskova"] <- "Venäjä"
	country[city=="Nanaimo BC"] <- "Kanada"
	country[city=="Narva"] <- "Viro"
	country[city=="New York NY"] <- "USA"
	country[city=="New York Mills MN"] <- "USA"
	country[city=="Oslo"] <- "Norja"
	country[city=="Oulu"] <- "Suomi"
	country[city=="Pariisi"] <- "Ranska"
	country[city=="Parkano"] <- "Suomi"
	country[city=="Philadelphia PA"] <- "USA"
	country[city=="Pietari"] <- "Venäjä"
	country[city=="Pietarsaari"] <- "Suomi"
	country[city=="Pori"] <- "Suomi"
	country[city=="Port Arthur ON"] <- "Kanada"
	country[city=="Portland OR"] <- "USA"
	country[city=="Porvoo"] <- "Suomi"
	country[city=="Pärnu"] <- "Viro"
	country[city=="Quincy MA"] <- "USA"
	country[city=="Raahe"] <- "Suomi"
	country[city=="Rauma"] <- "Suomi"
	country[city=="Riika"] <- "Latvia"
	country[city=="Rock Island IL"] <- "USA"
	country[city=="Rooma"] <- "Italia"
	country[city=="Rostock"] <- "Saksa"
	country[city=="Sairala"] <- "Suomi"
	country[city=="Savonlinna"] <- "Suomi"
	country[city=="Seattle WA"] <- "USA"
	country[city=="Sipoo"] <- "Suomi"
	country[city=="Skara"] <- "Ruotsi"
	country[city=="Smithville MN"] <- "USA"
	country[city=="Sortavala"] <- "Venäjä" #huom!
	country[city=="Strängnäs"] <- "Ruotsi"
	country[city=="Stuttgart"] <- "Saksa"
	country[city=="Superior WI"] <- "USA"
	country[city=="Tallinna"] <- "Viro"
	country[city=="Tammisaari"] <- "Suomi"
	country[city=="Tampere"] <- "Suomi"
	country[city=="Tartto"] <- "Viro"
	country[city=="Tukholma"] <- "Ruotsi"
	country[city=="Turenki"] <- "Suomi"
	country[city=="Turku"] <- "Suomi"
	country[city=="Uppsala"] <- "Ruotsi"
	country[city=="Uusikaarlepyy"] <- "Suomi"
	country[city=="Uusikaupunki"] <- "Suomi"
	country[city=="Vaasa"] <- "Suomi"
	country[city=="Varsova"] <- "Puola"
	country[city=="Viipuri"] <- "Suomi"
	country[city=="Vilna"] <- "Liettua"
	country[city=="Västerås"] <- "Ruotsi"
	country[city=="Weimar"] <- "Saksa"
	country[city=="Wien"] <- "Itävalta"
	country[city=="Wiesbaden"] <- "Saksa"
	country[city=="Wittenberg"] <- "Saksa"
	country[city=="Worcester MA"] <- "USA"
	country[city=="Örebro"] <- "Ruotsi"

	country
}
