#' @title deduce_country
#' @description Add country field to data frame based on city field
#'
#' @param df Main dataframe
#' @return Main dataframe
#'
#' @export
#' 
#' @author Niko Ilomäki \email{niko.ilomaki@@helsinki.fi}
#' @references See citation("fennica")
#' 
#' @examples \dontrun{df <- deduce_country(df)}
#' @keywords utilities
deduce_country <- function(df) {
	v <- df$city
	w <- rep(NA, data_size)
	w[v=="Almena WI"] <- "USA"
	w[v=="Altdorf"] <- "Saksa"
	w[v=="Amsterdam"] <- "Alankomaat"
	w[v=="Ashtabula OH"] <- "USA"
	w[v=="Astoria OR"] <- "USA"
	w[v=="Barcelona"] <- "Espanja"
	w[v=="Berliini"] <- "Saksa"
	w[v=="Boston MA"] <- "USA"
	w[v=="Braunschweig"] <- "Saksa"
	w[v=="Bridgeport CT"] <- "USA"
	w[v=="Bronx NY"] <- "USA"
	w[v=="Brooklyn NY"] <- "USA"
	w[v=="Calumet MI"] <- "USA"
	w[v=="Chicago IL"] <- "USA"
	w[v=="Chisholm MN"] <- "USA"
	w[v=="Cincinnati OH"] <- "USA"
	w[v=="Cleveland OH"] <- "USA"
	w[v=="Budapest"] <- "Unkari"
	w[v=="Dresden"] <- "Saksa"
	w[v=="Duluth MN"] <- "USA"
	w[v=="Espoo"] <- "Suomi"
	w[v=="Eura"] <- "Suomi"
	w[v=="Firenze"] <- "Italia"
	w[v=="Fitchburg MA"] <- "USA"
	w[v=="Forssa"] <- "Suomi"
	w[v=="Frankfurt"] <- "Saksa"
	w[v=="Giessen"] <- "Saksa"
	w[v=="Göteborg"] <- "Ruotsi"
	w[v=="Göttingen"] <- "Saksa"
	w[v=="Greifswald"] <- "Saksa"
	w[v=="Haaparanta"] <- "Suomi"
	w[v=="Hamina"] <- "Suomi"
	w[v=="Hampuri"] <- "Saksa"
	w[v=="Hancock MI"] <- "USA"
	w[v=="Hanko"] <- "Suomi"
	w[v=="Heinola"] <- "Suomi"
	w[v=="Helsinki"] <- "Suomi"
	w[v=="Hyvinkää"] <- "Suomi"
	w[v=="Hämeenlinna"] <- "Suomi"
	w[v=="Iisalmi"] <- "Suomi"
	w[v=="Ironwood MI"] <- "USA"
	w[v=="Ishpeming MI"] <- "USA"
	w[v=="Jena"] <- "Saksa"
	w[v=="Joensuu"] <- "Suomi"
	w[v=="Jyväskylä"] <- "Suomi"
	w[v=="Kajaani"] <- "Suomi"
	w[v=="Kaleva MI"] <- "USA"
	w[v=="Kaliningrad"] <- "Venäjä" #huom!
	w[v=="Karjaa"] <- "Suomi"
	w[v=="Kaskinen"] <- "Suomi"
	w[v=="Kemi"] <- "Suomi"
	w[v=="Kiel"] <- "Saksa"
	w[v=="Kokkola"] <- "Suomi"
	w[v=="Kotka"] <- "Suomi"
	w[v=="Kouvola"] <- "Suomi"
	w[v=="Kristiinankaupunki"] <- "Suomi"
	w[v=="Kruunupyy"] <- "Suomi"
	w[v=="Kuopio"] <- "Suomi"
	w[v=="Käkisalmi"] <- "Suomi"
	w[v=="Köln"] <- "Saksa"
	w[v=="Kööpenhamina"] <- "Tanska"
	w[v=="Laihia"] <- "Suomi"
	w[v=="Lahti"] <- "Suomi"
	w[v=="Lappeenranta"] <- "Suomi"
	w[v=="Lapua"] <- "Suomi"
	w[v=="Leiden"] <- "Saksa"
	w[v=="Leipzig"] <- "Saksa"
	w[v=="Linköping"] <- "Ruotsi"
	w[v=="Lontoo"] <- "UK"
	w[v=="Loviisa"] <- "Suomi"
	w[v=="Lund"] <- "Ruotsi"
	w[v=="Lyypekki"] <- "Saksa"
	w[v=="Maarianhamina"] <- "Suomi"
	w[v=="Magdeburg"] <- "Saksa"
	w[v=="Marburg"] <- "Saksa"
	w[v=="Mikkeli"] <- "Suomi"
	w[v=="Milwaukee WI"] <- "USA"
	w[v=="Minneapolis MN"] <- "USA"
	w[v=="Moskova"] <- "Venäjä"
	w[v=="Nanaimo BC"] <- "Kanada"
	w[v=="Narva"] <- "Viro"
	w[v=="New York NY"] <- "USA"
	w[v=="New York Mills MN"] <- "USA"
	w[v=="Oslo"] <- "Norja"
	w[v=="Oulu"] <- "Suomi"
	w[v=="Pariisi"] <- "Ranska"
	w[v=="Parkano"] <- "Suomi"
	w[v=="Philadelphia PA"] <- "USA"
	w[v=="Pietari"] <- "Venäjä"
	w[v=="Pietarsaari"] <- "Suomi"
	w[v=="Pori"] <- "Suomi"
	w[v=="Port Arthur ON"] <- "Kanada"
	w[v=="Portland OR"] <- "USA"
	w[v=="Porvoo"] <- "Suomi"
	w[v=="Pärnu"] <- "Viro"
	w[v=="Quincy MA"] <- "USA"
	w[v=="Raahe"] <- "Suomi"
	w[v=="Rauma"] <- "Suomi"
	w[v=="Riika"] <- "Latvia"
	w[v=="Rock Island IL"] <- "USA"
	w[v=="Rooma"] <- "Italia"
	w[v=="Rostock"] <- "Saksa"
	w[v=="Sairala"] <- "Suomi"
	w[v=="Savonlinna"] <- "Suomi"
	w[v=="Seattle WA"] <- "USA"
	w[v=="Sipoo"] <- "Suomi"
	w[v=="Skara"] <- "Ruotsi"
	w[v=="Smithville MN"] <- "USA"
	w[v=="Sortavala"] <- "Venäjä" #huom!
	w[v=="Strängnäs"] <- "Ruotsi"
	w[v=="Stuttgart"] <- "Saksa"
	w[v=="Superior WI"] <- "USA"
	w[v=="Tallinna"] <- "Viro"
	w[v=="Tammisaari"] <- "Suomi"
	w[v=="Tampere"] <- "Suomi"
	w[v=="Tartto"] <- "Viro"
	w[v=="Tukholma"] <- "Ruotsi"
	w[v=="Turenki"] <- "Suomi"
	w[v=="Turku"] <- "Suomi"
	w[v=="Uppsala"] <- "Ruotsi"
	w[v=="Uusikaarlepyy"] <- "Suomi"
	w[v=="Uusikaupunki"] <- "Suomi"
	w[v=="Vaasa"] <- "Suomi"
	w[v=="Varsova"] <- "Puola"
	w[v=="Viipuri"] <- "Suomi"
	w[v=="Vilna"] <- "Liettua"
	w[v=="Västerås"] <- "Ruotsi"
	w[v=="Weimar"] <- "Saksa"
	w[v=="Wien"] <- "Itävalta"
	w[v=="Wiesbaden"] <- "Saksa"
	w[v=="Wittenberg"] <- "Saksa"
	w[v=="Worcester MA"] <- "USA"
	w[v=="Örebro"] <- "Ruotsi"

	df$country <- w

	df
}
